/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\BAK 040X38X104.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  handle: ['Handle_5__Knob_', 'Handle_4', 'Handle_3', 'Handle_2', 'Handle_1'],
  pintu: ['CR_11'],
  ambalan: ['Ambalan'],
};

export function Model({ handle = '', pintu = '', ambalan = '' }) {
  const { nodes, materials } = useGLTF('/BAK 040X38X104.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BAK_40X38X104__2_1' }}>
            <group userData={{ name: 'BAK_40X38X104__2_' }}>
              <group userData={{ name: 'RANGKA_BAWAH_4_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh1.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh1' }}
                />
              </group>
              <group userData={{ name: 'RANGKA_BAWAH_4_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh2.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh2' }}
                />
              </group>
              <group userData={{ name: 'ALAS_RANGKA_4_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh3.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh3' }}
                />
              </group>
              <group userData={{ name: 'RANGKA_KANAN_KIRI_4_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh4.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh4' }}
                />
              </group>
              <group userData={{ name: 'RANGKA_KANAN_KIRI_4_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh5.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh5' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_5__Knob_'}
              userData={{ name: 'Handle_5__Knob_' }}
            >
              <group userData={{ name: 'Handle_5__knob_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh6.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh6' }}
                />
              </group>
              <group userData={{ name: 'Handle_5__knob_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh7.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh7' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_4'}
              userData={{ name: 'Handle_4' }}
            >
              <group userData={{ name: 'Handle_4_1' }}>
                <group userData={{ name: 'Group1' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh8.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh8' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh9.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh9' }}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh10.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh10' }}
                />
              </group>
              <group userData={{ name: 'Handle_4_2' }}>
                <group userData={{ name: 'Group2' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh11.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh11' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell1' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh12.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh12' }}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh13.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh13' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_3'}
              userData={{ name: 'Handle_3' }}
            >
              <group userData={{ name: 'Handle_3_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh14.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh14' }}
                />
              </group>
              <group userData={{ name: 'Handle_3_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh15.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh15' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_2'}
              userData={{ name: 'Handle_2' }}
            >
              <group userData={{ name: 'Handle_2_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh16.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh16' }}
                />
              </group>
              <group userData={{ name: 'Handle_2_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh17.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh17' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_1'}
              userData={{ name: 'Handle_1' }}
            >
              <group userData={{ name: 'Knob_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh18.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh18' }}
                />
              </group>
              <group userData={{ name: 'Knob_1_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh19.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh19' }}
                />
              </group>
            </group>
            <group visible={pintu === 'CR_11'} userData={{ name: 'CR_11' }}>
              <group userData={{ name: 'BAK_40X38X104__2_12' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh20.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh20' }}
                />
              </group>
              <group userData={{ name: 'BAK_40X38X104__2_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh21.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh21' }}
                />
              </group>
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_3' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh22.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh22' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_4' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh23.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh23' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh24.geometry}
                material={materials.KAYU_SOLID}
                userData={{ name: 'Mesh24' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_6' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh25.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh25' }}
              />
            </group>
            <group
              visible={ambalan === 'Ambalan'}
              userData={{ name: 'Ambalan' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh26.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh26' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_7' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh27.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh27' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_8' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh28.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh28' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_9' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh29.geometry}
                material={materials.KAYU_SOLID}
                userData={{ name: 'Mesh29' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_10' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh30.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh30' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh31.geometry}
                material={materials.KAYU_SOLID}
                userData={{ name: 'Mesh31' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X104__2_1213' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh32.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh32' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BAK 040X38X104.glb');
