/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\BAK 040X38X40.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  handle: ['Handle_5__knob_', 'Handle_4', 'Handle_3', 'Knob_1', 'Handle_2'],
  pintu: ['CR_11', 'CR_12', 'CR_13'],
  isian: ['Ambalan'],
};

export function Model({ handle = '', pintu = '', isian = '' }) {
  const { nodes, materials } = useGLTF('/BAK 040X38X40.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BAK_40X38X40_1' }}>
            <group visible={handle === 'Knob_1'} userData={{ name: 'Knob_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.MyFrontMaterial1}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X40' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X40_1_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh3' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X40_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh4.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh4' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X40_3' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh5.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh5' }}
              />
            </group>
            <group visible={pintu === 'CR_12'} userData={{ name: 'CR_12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh6.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh6' }}
              />
            </group>
            <group visible={pintu === 'CR_13'} userData={{ name: 'CR_13' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh7.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh7' }}
              />
            </group>
            <group visible={pintu === 'CR_11'} userData={{ name: 'CR_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh8.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh8' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X40_4' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh9.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh9' }}
              />
            </group>
            <group userData={{ name: 'BAK_40X38X40_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh10.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh10' }}
              />
            </group>
            <group
              visible={handle === 'Handle_2'}
              userData={{ name: 'Handle_2' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh11.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh11' }}
              />
            </group>
            <group
              visible={handle === 'Handle_5__knob_'}
              userData={{ name: 'Handle_5__knob_' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh12.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh12' }}
              />
            </group>
            <group
              visible={handle === 'Handle_3'}
              userData={{ name: 'Handle_3' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh13.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh13' }}
              />
            </group>
            <group
              visible={(handle === 'Handle_4')}
              userData={{ name: 'Handle_4' }}
            >
              <group userData={{ name: 'Group1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh14.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh14' }}
                />
              </group>
              <group userData={{ name: 'OuterShell' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh15.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh15' }}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh16.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh16' }}
              />
            </group>
            <group visible={isian === 'Ambalan'} userData={{ name: 'Ambalan' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh17.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh17' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BAK 040X38X40.glb');