/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\BAK 090X38X104.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  handle: ['Handle_5__Knob_', 'Handle_4', 'Handle_3', 'Handle_2', 'Handle_1'],
  pintu: ['CR_11'],
  isian: ['appliances_piring', 'Ambalan'],
};

export const key = 'BAK_090X38X104';

export function Model({ handle = '', pintu = '', isian = '' }) {
  const { nodes, materials } = useGLTF('/BAK 090X38X104.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group
            visible={isian === 'appliances_piring'}
            userData={{ name: 'appliances_piring' }}
          >
            <group userData={{ name: 'Group1' }}>
              <group userData={{ name: 'Group2' }}>
                <group userData={{ name: 'Group3' }}>
                  <group userData={{ name: 'Group4' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh1.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh1' }}
                    />
                  </group>
                  <group userData={{ name: 'Group5' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh2.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh2' }}
                    />
                  </group>
                  <group userData={{ name: 'Group6' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh3.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh3' }}
                    />
                  </group>
                  <group userData={{ name: 'Group7' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh4.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh4' }}
                    />
                  </group>
                  <group userData={{ name: 'Group8' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh5.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh5' }}
                    />
                  </group>
                  <group userData={{ name: 'Group9' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh6.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh6' }}
                    />
                  </group>
                  <group userData={{ name: 'Group10' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh7.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh7' }}
                    />
                  </group>
                  <group userData={{ name: 'Group11' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh8.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh8' }}
                    />
                  </group>
                  <group userData={{ name: 'Group12' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh9.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh9' }}
                    />
                  </group>
                  <group userData={{ name: 'Group13' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh10.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh10' }}
                    />
                  </group>
                  <group userData={{ name: 'Group14' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh11.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh11' }}
                    />
                  </group>
                  <group userData={{ name: 'Group15' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh12.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh12' }}
                    />
                  </group>
                  <group userData={{ name: 'Group16' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh13.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh13' }}
                    />
                  </group>
                  <group userData={{ name: 'Group17' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh14.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh14' }}
                    />
                  </group>
                  <group userData={{ name: 'Group18' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh15.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh15' }}
                    />
                  </group>
                  <group userData={{ name: 'Group19' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh16.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh16' }}
                    />
                  </group>
                  <group userData={{ name: 'Group20' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh17.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh17' }}
                    />
                  </group>
                  <group userData={{ name: 'Group21' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh18.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh18' }}
                    />
                  </group>
                  <group userData={{ name: 'Group22' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh19.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh19' }}
                    />
                  </group>
                  <group userData={{ name: 'Group23' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh20.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh20' }}
                    />
                  </group>
                  <group userData={{ name: 'Group24' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh21.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh21' }}
                    />
                  </group>
                  <group userData={{ name: 'Group25' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh22.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh22' }}
                    />
                  </group>
                  <group userData={{ name: 'Group26' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh23.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh23' }}
                    />
                  </group>
                  <group userData={{ name: 'Group27' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh24.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh24' }}
                    />
                  </group>
                  <group userData={{ name: 'Group28' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh25.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh25' }}
                    />
                  </group>
                  <group userData={{ name: 'Group29' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh26.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh26' }}
                    />
                  </group>
                  <group userData={{ name: 'Group30' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh27.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh27' }}
                    />
                  </group>
                  <group userData={{ name: 'Agrupar_22_1' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh28.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh28' }}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group31' }}>
                  <group userData={{ name: 'Group32' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh29.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh29' }}
                    />
                  </group>
                  <group userData={{ name: 'Group33' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh30.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh30' }}
                    />
                  </group>
                  <group userData={{ name: 'Group34' }}>
                    <group userData={{ name: 'Group35' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh31.geometry}
                        material={materials.FrontColor}
                        userData={{ name: 'Mesh31' }}
                      />
                    </group>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh32.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh32' }}
                    />
                  </group>
                  <group userData={{ name: 'Group36' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh33.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh33' }}
                    />
                  </group>
                  <group userData={{ name: 'Group37' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh34.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh34' }}
                    />
                  </group>
                </group>
              </group>
              <group userData={{ name: 'Group38' }}>
                <group userData={{ name: 'Group39' }}>
                  <group userData={{ name: 'Group40' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh35.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh35' }}
                    />
                  </group>
                  <group userData={{ name: 'Group41' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh36.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh36' }}
                    />
                  </group>
                  <group userData={{ name: 'Group42' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh37.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh37' }}
                    />
                  </group>
                  <group userData={{ name: 'Group43' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh38.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh38' }}
                    />
                  </group>
                  <group userData={{ name: 'Group44' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh39.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh39' }}
                    />
                  </group>
                  <group userData={{ name: 'Group45' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh40.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh40' }}
                    />
                  </group>
                  <group userData={{ name: 'Group46' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh41.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh41' }}
                    />
                  </group>
                  <group userData={{ name: 'Group47' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh42.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh42' }}
                    />
                  </group>
                  <group userData={{ name: 'Group48' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh43.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh43' }}
                    />
                  </group>
                  <group userData={{ name: 'Group49' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh44.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh44' }}
                    />
                  </group>
                  <group userData={{ name: 'Group50' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh45.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh45' }}
                    />
                  </group>
                  <group userData={{ name: 'Group51' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh46.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh46' }}
                    />
                  </group>
                  <group userData={{ name: 'Group52' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh47.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh47' }}
                    />
                  </group>
                  <group userData={{ name: 'Group53' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh48.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh48' }}
                    />
                  </group>
                  <group userData={{ name: 'Group54' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh49.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh49' }}
                    />
                  </group>
                  <group userData={{ name: 'Group55' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh50.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh50' }}
                    />
                  </group>
                  <group userData={{ name: 'Group56' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh51.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh51' }}
                    />
                  </group>
                  <group userData={{ name: 'Group57' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh52.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh52' }}
                    />
                  </group>
                  <group userData={{ name: 'Group58' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh53.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh53' }}
                    />
                  </group>
                  <group userData={{ name: 'Group59' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh54.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh54' }}
                    />
                  </group>
                  <group userData={{ name: 'Group60' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh55.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh55' }}
                    />
                  </group>
                  <group userData={{ name: 'Group61' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh56.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh56' }}
                    />
                  </group>
                  <group userData={{ name: 'Group62' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh57.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh57' }}
                    />
                  </group>
                  <group userData={{ name: 'Group63' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh58.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh58' }}
                    />
                  </group>
                  <group userData={{ name: 'Group64' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh59.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh59' }}
                    />
                  </group>
                  <group userData={{ name: 'Group65' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh60.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh60' }}
                    />
                  </group>
                  <group userData={{ name: 'Group66' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh61.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh61' }}
                    />
                  </group>
                  <group userData={{ name: 'Agrupar_22_2' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh62.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh62' }}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group67' }}>
                  <group userData={{ name: 'Group68' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh63.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh63' }}
                    />
                  </group>
                  <group userData={{ name: 'Group69' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh64.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh64' }}
                    />
                  </group>
                  <group userData={{ name: 'Group70' }}>
                    <group userData={{ name: 'Group71' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh65.geometry}
                        material={materials.FrontColor}
                        userData={{ name: 'Mesh65' }}
                      />
                    </group>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh66.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh66' }}
                    />
                  </group>
                  <group userData={{ name: 'Group72' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh67.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh67' }}
                    />
                  </group>
                  <group userData={{ name: 'Group73' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh68.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh68' }}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group userData={{ name: 'Group74' }}>
              <group userData={{ name: 'Group75' }}>
                <group userData={{ name: 'Group76' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh69.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh69' }}
                  />
                </group>
                <group userData={{ name: 'Group77' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh70.geometry}
                    material={materials.Color_007}
                    userData={{ name: 'Mesh70' }}
                  />
                </group>
                <group userData={{ name: 'Group78' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh71.geometry}
                    material={materials.Color_007}
                    userData={{ name: 'Mesh71' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Group79' }}>
                <group userData={{ name: 'Group80' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh72.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh72' }}
                  />
                </group>
                <group userData={{ name: 'Group81' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh73.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh73' }}
                  />
                </group>
                <group userData={{ name: 'Group82' }}>
                  <group userData={{ name: 'Group83' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh74.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh74' }}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh75.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh75' }}
                  />
                </group>
                <group userData={{ name: 'Group84' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh76.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh76' }}
                  />
                </group>
                <group userData={{ name: 'Group85' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh77.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh77' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Group86' }}>
                <group userData={{ name: 'Group87' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh78.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh78' }}
                  />
                </group>
                <group userData={{ name: 'Group88' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh79.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh79' }}
                  />
                </group>
                <group userData={{ name: 'Group89' }}>
                  <group userData={{ name: 'Group90' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.Mesh80.geometry}
                      material={materials.FrontColor}
                      userData={{ name: 'Mesh80' }}
                    />
                  </group>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh81.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh81' }}
                  />
                </group>
                <group userData={{ name: 'Group91' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh82.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh82' }}
                  />
                </group>
                <group userData={{ name: 'Group92' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh83.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh83' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_1' }}>
                <group userData={{ name: 'Group93' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh84.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh84' }}
                  />
                </group>
                <group userData={{ name: 'Group94' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh85.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh85' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_2' }}>
                <group userData={{ name: 'Group95' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh86.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh86' }}
                  />
                </group>
                <group userData={{ name: 'Group96' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh87.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh87' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_3' }}>
                <group userData={{ name: 'Group97' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh88.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh88' }}
                  />
                </group>
                <group userData={{ name: 'Group98' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh89.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh89' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_4' }}>
                <group userData={{ name: 'Group99' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh90.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh90' }}
                  />
                </group>
                <group userData={{ name: 'Group100' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh91.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh91' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_5' }}>
                <group userData={{ name: 'Group101' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh92.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh92' }}
                  />
                </group>
                <group userData={{ name: 'Group102' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh93.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh93' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_6' }}>
                <group userData={{ name: 'Group103' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh94.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh94' }}
                  />
                </group>
                <group userData={{ name: 'Group104' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh95.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh95' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_7' }}>
                <group userData={{ name: 'Group105' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh96.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh96' }}
                  />
                </group>
                <group userData={{ name: 'Group106' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh97.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh97' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_8' }}>
                <group userData={{ name: 'Group107' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh98.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh98' }}
                  />
                </group>
                <group userData={{ name: 'Group108' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh99.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh99' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_9' }}>
                <group userData={{ name: 'Group109' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh100.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh100' }}
                  />
                </group>
                <group userData={{ name: 'Group110' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh101.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh101' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_10' }}>
                <group userData={{ name: 'Group111' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh102.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh102' }}
                  />
                </group>
                <group userData={{ name: 'Group112' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh103.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh103' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_11' }}>
                <group userData={{ name: 'Group113' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh104.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh104' }}
                  />
                </group>
                <group userData={{ name: 'Group114' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh105.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh105' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_12' }}>
                <group userData={{ name: 'Group115' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh106.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh106' }}
                  />
                </group>
                <group userData={{ name: 'Group116' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh107.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh107' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_13' }}>
                <group userData={{ name: 'Group117' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh108.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh108' }}
                  />
                </group>
                <group userData={{ name: 'Group118' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh109.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh109' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_14' }}>
                <group userData={{ name: 'Group119' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh110.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh110' }}
                  />
                </group>
                <group userData={{ name: 'Group120' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh111.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh111' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_15' }}>
                <group userData={{ name: 'Group121' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh112.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh112' }}
                  />
                </group>
                <group userData={{ name: 'Group122' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh113.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh113' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_16' }}>
                <group userData={{ name: 'Group123' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh114.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh114' }}
                  />
                </group>
                <group userData={{ name: 'Group124' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh115.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh115' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_17' }}>
                <group userData={{ name: 'Group125' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh116.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh116' }}
                  />
                </group>
                <group userData={{ name: 'Group126' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh117.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh117' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_18' }}>
                <group userData={{ name: 'Group127' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh118.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh118' }}
                  />
                </group>
                <group userData={{ name: 'Group128' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh119.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh119' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_19' }}>
                <group userData={{ name: 'Group129' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh120.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh120' }}
                  />
                </group>
                <group userData={{ name: 'Group130' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh121.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh121' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_20' }}>
                <group userData={{ name: 'Group131' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh122.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh122' }}
                  />
                </group>
                <group userData={{ name: 'Group132' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh123.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh123' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_21' }}>
                <group userData={{ name: 'Group133' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh124.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh124' }}
                  />
                </group>
                <group userData={{ name: 'Group134' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh125.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh125' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_22' }}>
                <group userData={{ name: 'Group135' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh126.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh126' }}
                  />
                </group>
                <group userData={{ name: 'Group136' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh127.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh127' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_23' }}>
                <group userData={{ name: 'Group137' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh128.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh128' }}
                  />
                </group>
                <group userData={{ name: 'Group138' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh129.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh129' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_24' }}>
                <group userData={{ name: 'Group139' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh130.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh130' }}
                  />
                </group>
                <group userData={{ name: 'Group140' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh131.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh131' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_25' }}>
                <group userData={{ name: 'Group141' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh132.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh132' }}
                  />
                </group>
                <group userData={{ name: 'Group142' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh133.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh133' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_26' }}>
                <group userData={{ name: 'Group143' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh134.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh134' }}
                  />
                </group>
                <group userData={{ name: 'Group144' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh135.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh135' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_27' }}>
                <group userData={{ name: 'Group145' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh136.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh136' }}
                  />
                </group>
                <group userData={{ name: 'Group146' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh137.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh137' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_28' }}>
                <group userData={{ name: 'Group147' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh138.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh138' }}
                  />
                </group>
                <group userData={{ name: 'Group148' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh139.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh139' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_29' }}>
                <group userData={{ name: 'Group149' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh140.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh140' }}
                  />
                </group>
                <group userData={{ name: 'Group150' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh141.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh141' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_30' }}>
                <group userData={{ name: 'Group151' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh142.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh142' }}
                  />
                </group>
                <group userData={{ name: 'Group152' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh143.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh143' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_31' }}>
                <group userData={{ name: 'Group153' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh144.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh144' }}
                  />
                </group>
                <group userData={{ name: 'Group154' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh145.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh145' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_32' }}>
                <group userData={{ name: 'Group155' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh146.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh146' }}
                  />
                </group>
                <group userData={{ name: 'Group156' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh147.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh147' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_33' }}>
                <group userData={{ name: 'Group157' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh148.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh148' }}
                  />
                </group>
                <group userData={{ name: 'Group158' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh149.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh149' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_34' }}>
                <group userData={{ name: 'Group159' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh150.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh150' }}
                  />
                </group>
                <group userData={{ name: 'Group160' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh151.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh151' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_35' }}>
                <group userData={{ name: 'Group161' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh152.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh152' }}
                  />
                </group>
                <group userData={{ name: 'Group162' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh153.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh153' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_36' }}>
                <group userData={{ name: 'Group163' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh154.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh154' }}
                  />
                </group>
                <group userData={{ name: 'Group164' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh155.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh155' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_37' }}>
                <group userData={{ name: 'Group165' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh156.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh156' }}
                  />
                </group>
                <group userData={{ name: 'Group166' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh157.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh157' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_38' }}>
                <group userData={{ name: 'Group167' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh158.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh158' }}
                  />
                </group>
                <group userData={{ name: 'Group168' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh159.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh159' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_39' }}>
                <group userData={{ name: 'Group169' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh160.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh160' }}
                  />
                </group>
                <group userData={{ name: 'Group170' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh161.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh161' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_40' }}>
                <group userData={{ name: 'Group171' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh162.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh162' }}
                  />
                </group>
                <group userData={{ name: 'Group172' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh163.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh163' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_41' }}>
                <group userData={{ name: 'Group173' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh164.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh164' }}
                  />
                </group>
                <group userData={{ name: 'Group174' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh165.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh165' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_42' }}>
                <group userData={{ name: 'Group175' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh166.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh166' }}
                  />
                </group>
                <group userData={{ name: 'Group176' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh167.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh167' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_43' }}>
                <group userData={{ name: 'Group177' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh168.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh168' }}
                  />
                </group>
                <group userData={{ name: 'Group178' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh169.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh169' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_44' }}>
                <group userData={{ name: 'Group179' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh170.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh170' }}
                  />
                </group>
                <group userData={{ name: 'Group180' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh171.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh171' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_45' }}>
                <group userData={{ name: 'Group181' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh172.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh172' }}
                  />
                </group>
                <group userData={{ name: 'Group182' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh173.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh173' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_46' }}>
                <group userData={{ name: 'Group183' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh174.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh174' }}
                  />
                </group>
                <group userData={{ name: 'Group184' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh175.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh175' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_47' }}>
                <group userData={{ name: 'Group185' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh176.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh176' }}
                  />
                </group>
                <group userData={{ name: 'Group186' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh177.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh177' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_48' }}>
                <group userData={{ name: 'Group187' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh178.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh178' }}
                  />
                </group>
                <group userData={{ name: 'Group188' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh179.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh179' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_49' }}>
                <group userData={{ name: 'Group189' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh180.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh180' }}
                  />
                </group>
                <group userData={{ name: 'Group190' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh181.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh181' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_50' }}>
                <group userData={{ name: 'Group191' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh182.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh182' }}
                  />
                </group>
                <group userData={{ name: 'Group192' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh183.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh183' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_51' }}>
                <group userData={{ name: 'Group193' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh184.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh184' }}
                  />
                </group>
                <group userData={{ name: 'Group194' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh185.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh185' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_52' }}>
                <group userData={{ name: 'Group195' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh186.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh186' }}
                  />
                </group>
                <group userData={{ name: 'Group196' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh187.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh187' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_53' }}>
                <group userData={{ name: 'Group197' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh188.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh188' }}
                  />
                </group>
                <group userData={{ name: 'Group198' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh189.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh189' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_54' }}>
                <group userData={{ name: 'Group199' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh190.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh190' }}
                  />
                </group>
                <group userData={{ name: 'Group200' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh191.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh191' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_55' }}>
                <group userData={{ name: 'Group201' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh192.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh192' }}
                  />
                </group>
                <group userData={{ name: 'Group202' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh193.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh193' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_56' }}>
                <group userData={{ name: 'Group203' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh194.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh194' }}
                  />
                </group>
                <group userData={{ name: 'Group204' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh195.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh195' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_57' }}>
                <group userData={{ name: 'Group205' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh196.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh196' }}
                  />
                </group>
                <group userData={{ name: 'Group206' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh197.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh197' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_22_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh198.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh198' }}
                />
              </group>
              <group userData={{ name: 'Agrupar_28_58' }}>
                <group userData={{ name: 'Group207' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh199.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh199' }}
                  />
                </group>
                <group userData={{ name: 'Group208' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh200.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh200' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_59' }}>
                <group userData={{ name: 'Group209' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh201.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh201' }}
                  />
                </group>
                <group userData={{ name: 'Group210' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh202.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh202' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_60' }}>
                <group userData={{ name: 'Group211' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh203.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh203' }}
                  />
                </group>
                <group userData={{ name: 'Group212' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh204.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh204' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Agrupar_28_61' }}>
                <group userData={{ name: 'Group213' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh205.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh205' }}
                  />
                </group>
                <group userData={{ name: 'Group214' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh206.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh206' }}
                  />
                </group>
              </group>
            </group>
          </group>
          <group userData={{ name: 'BAK_90X38X104__2_1' }}>
            <group userData={{ name: 'BAK_90X38X104__2_' }}>
              <group userData={{ name: 'RANGKA_BAWAH_11_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh207.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh207' }}
                />
              </group>
              <group userData={{ name: 'RANGKA_BAWAH_11_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh208.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh208' }}
                />
              </group>
              <group userData={{ name: 'ALAS_RANGKA_11_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh209.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh209' }}
                />
              </group>
              <group userData={{ name: 'RANGKA_KANAN_KIRI_11_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh210.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh210' }}
                />
              </group>
              <group userData={{ name: 'RANGKA_KANAN_KIRI_11_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh211.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh211' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_5__Knob_'}
              userData={{ name: 'Handle_5__Knob_' }}
            >
              <group userData={{ name: 'Handle_5__knob_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh212.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh212' }}
                />
              </group>
              <group userData={{ name: 'Handle_5__knob_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh213.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh213' }}
                />
              </group>
              <group userData={{ name: 'Handle_5__knob_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh214.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh214' }}
                />
              </group>
              <group userData={{ name: 'Handle_5__knob_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh215.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh215' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_4'}
              userData={{ name: 'Handle_4' }}
            >
              <group userData={{ name: 'Handle_4_1' }}>
                <group userData={{ name: 'Group215' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh216.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh216' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh217.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh217' }}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh218.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh218' }}
                />
              </group>
              <group userData={{ name: 'Handle_4_2' }}>
                <group userData={{ name: 'Group216' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh219.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh219' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell1' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh220.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh220' }}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh221.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh221' }}
                />
              </group>
              <group userData={{ name: 'Handle_4_3' }}>
                <group userData={{ name: 'Group217' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh222.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh222' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell2' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh223.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh223' }}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh224.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh224' }}
                />
              </group>
              <group userData={{ name: 'Handle_4_4' }}>
                <group userData={{ name: 'Group218' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh225.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh225' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell3' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh226.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh226' }}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh227.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh227' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_3'}
              userData={{ name: 'Handle_3' }}
            >
              <group userData={{ name: 'Handle_3_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh228.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh228' }}
                />
              </group>
              <group userData={{ name: 'Handle_3_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh229.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh229' }}
                />
              </group>
              <group userData={{ name: 'Handle_3_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh230.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh230' }}
                />
              </group>
              <group userData={{ name: 'Handle_3_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh231.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh231' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_2'}
              userData={{ name: 'Handle_2' }}
            >
              <group userData={{ name: 'Handle_2_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh232.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh232' }}
                />
              </group>
              <group userData={{ name: 'Handle_2_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh233.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh233' }}
                />
              </group>
              <group userData={{ name: 'Handle_2_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh234.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh234' }}
                />
              </group>
              <group userData={{ name: 'Handle_2_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh235.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh235' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'Handle_1'}
              userData={{ name: 'Handle_1' }}
            >
              <group userData={{ name: 'Knob_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh236.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh236' }}
                />
              </group>
              <group userData={{ name: 'Knob_1_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh237.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh237' }}
                />
              </group>
              <group userData={{ name: 'Knob_1_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh238.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh238' }}
                />
              </group>
              <group userData={{ name: 'Knob_1_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh239.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh239' }}
                />
              </group>
            </group>
            <group visible={pintu === 'CR_11'} userData={{ name: 'CR_11' }}>
              <group userData={{ name: 'BAK_90X38X104__2_12' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh240.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh240' }}
                />
              </group>
              <group userData={{ name: 'BAK_90X38X104__2_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh241.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh241' }}
                />
              </group>
              <group userData={{ name: 'BAK_90X38X104__2_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh242.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh242' }}
                />
              </group>
              <group userData={{ name: 'BAK_90X38X104__2_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh243.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh243' }}
                />
              </group>
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh244.geometry}
                material={materials.KAYU_SOLID}
                userData={{ name: 'Mesh244' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_6' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh245.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh245' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_7' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh246.geometry}
                material={materials.KAYU_SOLID}
                userData={{ name: 'Mesh246' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_8' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh247.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh247' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_9' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh248.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh248' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_10' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh249.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh249' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh250.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh250' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_1213' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh251.geometry}
                material={materials.KAYU_SOLID}
                userData={{ name: 'Mesh251' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_13' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh252.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh252' }}
              />
            </group>
            <group userData={{ name: 'BAK_90X38X104__2_14' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh253.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh253' }}
              />
            </group>
          </group>
          <group visible={isian === 'Ambalan'} userData={{ name: 'Ambalan' }}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh254.geometry}
              material={materials.FrontColor}
              userData={{ name: 'Mesh254' }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BAK 090X38X104.glb');
