/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 .\public\BAW 110X60X40.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  pintu: ['CR_11', 'CR_12', 'CR_13'],
};

export function Model({ pintu = '' }) {
  const { nodes, materials } = useGLTF('/BAW 110X60X40.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BAW_110X60X40_1' }}>
            <group visible={pintu === 'CR_12'} userData={{ name: 'CR_12' }}>
              <group userData={{ name: 'BAW_110X60X40' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh1.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh1' }}
                />
              </group>
              <group userData={{ name: 'BAW_110X60X40_1_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh2.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh2' }}
                />
              </group>
            </group>
            <group visible={pintu === 'CR_13'} userData={{ name: 'CR_13' }}>
              <group userData={{ name: 'BAW_110X60X40_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh3.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh3' }}
                />
              </group>
              <group userData={{ name: 'BAW_110X60X40_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh4.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh4' }}
                />
              </group>
            </group>
            <group visible={pintu === 'CR_11'} userData={{ name: 'CR_11' }}>
              <group userData={{ name: 'BAW_110X60X40_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh5.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh5' }}
                />
              </group>
              <group userData={{ name: 'BAW_110X60X40_5' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh6.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh6' }}
                />
              </group>
            </group>
            <group userData={{ name: 'BAW_110X60X40_6' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh7.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh7' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_7' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh8.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh8' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_8' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh9.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh9' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_9' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh10.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh10' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_10' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh11.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh11' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh12.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh12' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BAW 110X60X40.glb');
