/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\BBK 020X60X85.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  plint: ['CB1', 'CB2', 'Plint_CB8', 'CB4'],
  handle: ['Knob_1', 'Handle_2', 'Handle_4', 'Handle_5__knob_', 'Handle_3'],
  pintu: ['CR_11', 'CR_13', 'CR_12'],
  isian: ['Appliances_botol'],
};

export function Model({ plint = '', handle = '', pintu = '', isian = '' }) {
  const { nodes, materials } = useGLTF('/BBK 020X60X85.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BBK_20X60X85_1' }}>
            <group visible={handle === 'Knob_1'} userData={{ name: 'Knob_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.MyFrontMaterial1}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group visible={pintu === 'CR_11'} userData={{ name: 'CR_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group visible={pintu === 'CR_13'} userData={{ name: 'CR_13' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh3' }}
              />
            </group>
            <group visible={pintu === 'CR_12'} userData={{ name: 'CR_12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh4.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh4' }}
              />
            </group>
            <group
              visible={handle === 'Handle_2'}
              userData={{ name: 'Handle_2' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh5.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh5' }}
              />
            </group>
            <group
              visible={handle === 'Handle_4'}
              userData={{ name: 'Handle_4' }}
            >
              <group userData={{ name: 'Group1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh6.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh6' }}
                />
              </group>
              <group userData={{ name: 'OuterShell' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh7.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh7' }}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh8.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh8' }}
              />
            </group>
            <group
              visible={handle === 'Handle_5__knob_'}
              userData={{ name: 'Handle_5__knob_' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh9.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh9' }}
              />
            </group>
            <group
              visible={handle === 'Handle_3'}
              userData={{ name: 'Handle_3' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh10.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh10' }}
              />
            </group>
            <group
              visible={isian === 'Appliances_botol'}
              userData={{ name: 'Appliances_botol' }}
            >
              <group userData={{ name: 'Group2' }}>
                <group userData={{ name: 'Group3' }}>
                  <group userData={{ name: 'Group4' }}>
                    <group userData={{ name: 'Group5' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh11.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh11' }}
                      />
                    </group>
                    <group userData={{ name: 'Group6' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh12.geometry}
                        material={materials.Color_000}
                        userData={{ name: 'Mesh12' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh13' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_12.geometry}
                        material={materials.Color_M00}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_12_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group7' }}>
                    <group userData={{ name: 'Group8' }}>
                      <group userData={{ name: 'Untitled1' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh14.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh14' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled2' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh15.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh15' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Group9' }}>
                      <group userData={{ name: 'Untitled3' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh16.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh16' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled4' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh17.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh17' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Mesh18' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_17.geometry}
                        material={materials.Color_M00}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_17_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group10' }}>
                    <group userData={{ name: 'Group11' }}>
                      <group userData={{ name: 'Group12' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh19.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh19' }}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh20.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh20' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh21' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_20.geometry}
                        material={materials.Color_M00}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_20_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                </group>
                <group userData={{ name: 'Group14' }}>
                  <group userData={{ name: 'Group15' }}>
                    <group userData={{ name: 'Group16' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh22.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh22' }}
                      />
                    </group>
                    <group userData={{ name: 'Group17' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh23.geometry}
                        material={materials.Color_000}
                        userData={{ name: 'Mesh23' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh24' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_23.geometry}
                        material={materials.Color_M00}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_23_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group18' }}>
                    <group userData={{ name: 'Group19' }}>
                      <group userData={{ name: 'Untitled5' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh25.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh25' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled6' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh26.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh26' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Group20' }}>
                      <group userData={{ name: 'Untitled7' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh27.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh27' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled8' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh28.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh28' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Mesh29' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_28.geometry}
                        material={materials.Color_M00}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_28_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group21' }}>
                    <group userData={{ name: 'Group22' }}>
                      <group userData={{ name: 'Group23' }}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Mesh30.geometry}
                          material={materials.Color_M00}
                          userData={{ name: 'Mesh30' }}
                        />
                      </group>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh31.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh31' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh32' }}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_31.geometry}
                        material={materials.Color_M00}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh_31_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                </group>
              </group>
              <group userData={{ name: 'Group25' }}>
                <group userData={{ name: 'Mesh33' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_32.geometry}
                    material={materials.Color_M00}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_32_1.geometry}
                    material={materials.whiskey_bottle}
                  />
                </group>
              </group>
              <group userData={{ name: 'Group26' }}>
                <group userData={{ name: 'Group27' }}>
                  <group userData={{ name: 'Mesh34' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.mesh_33.geometry}
                      material={materials.bottle}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.mesh_33_1.geometry}
                      material={materials.Color_M00}
                    />
                  </group>
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh35.geometry}
                  material={materials.bottle}
                  userData={{ name: 'Mesh35' }}
                />
              </group>
              <group userData={{ name: 'Group28' }}>
                <group userData={{ name: 'Group29' }}>
                  <group userData={{ name: 'Mesh36' }}>
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.mesh_35.geometry}
                      material={materials.bottle}
                    />
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={nodes.mesh_35_1.geometry}
                      material={materials.Color_M00}
                    />
                  </group>
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh37.geometry}
                  material={materials.bottle}
                  userData={{ name: 'Mesh37' }}
                />
              </group>
              <group userData={{ name: 'Group30' }}>
                <group userData={{ name: 'Mesh38' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_37.geometry}
                    material={materials.Color_M00}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mesh_37_1.geometry}
                    material={materials.whiskey_bottle}
                  />
                </group>
              </group>
              <group userData={{ name: 'Component_27_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh39.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh39' }}
                />
              </group>
              <group userData={{ name: 'Component_27_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh40.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh40' }}
                />
              </group>
              <group userData={{ name: 'Component_27_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh41.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh41' }}
                />
              </group>
              <group userData={{ name: 'Component_27_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh42.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh42' }}
                />
              </group>
              <group userData={{ name: 'Component_27_5' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh43.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh43' }}
                />
              </group>
              <group userData={{ name: 'Component_27_6' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh44.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh44' }}
                />
              </group>
              <group userData={{ name: 'Component_27_7' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh45.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh45' }}
                />
              </group>
              <group userData={{ name: 'Component_27_8' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh46.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh46' }}
                />
              </group>
              <group userData={{ name: 'Component_27_9' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh47.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh47' }}
                />
              </group>
              <group userData={{ name: 'Component_27_10' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh48.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh48' }}
                />
              </group>
              <group userData={{ name: 'Component_26_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh49.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh49' }}
                />
              </group>
              <group userData={{ name: 'Component_26_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh50.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh50' }}
                />
              </group>
              <group userData={{ name: 'Component_26_3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh51.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh51' }}
                />
              </group>
              <group userData={{ name: 'Component_26_4' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh52.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh52' }}
                />
              </group>
              <group userData={{ name: 'Component_27_11' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh53.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh53' }}
                />
              </group>
              <group userData={{ name: 'Component_27_12' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh54.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh54' }}
                />
              </group>
              <group userData={{ name: 'Component_27_13' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh55.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh55' }}
                />
              </group>
              <group userData={{ name: 'Component_27_14' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh56.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh56' }}
                />
              </group>
              <group userData={{ name: 'Component_27_15' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh57.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh57' }}
                />
              </group>
              <group userData={{ name: 'Component_27_16' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh58.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh58' }}
                />
              </group>
              <group userData={{ name: 'Component_27_17' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh59.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh59' }}
                />
              </group>
              <group userData={{ name: 'Component_27_18' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh60.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh60' }}
                />
              </group>
              <group userData={{ name: 'Component_27_19' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh61.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh61' }}
                />
              </group>
              <group userData={{ name: 'Component_26_5' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh62.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh62' }}
                />
              </group>
              <group userData={{ name: 'Component_27_20' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh63.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh63' }}
                />
              </group>
              <group userData={{ name: 'Component_27_21' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh64.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh64' }}
                />
              </group>
              <group userData={{ name: 'Component_27_22' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh65.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh65' }}
                />
              </group>
              <group userData={{ name: 'Component_27_23' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh66.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh66' }}
                />
              </group>
              <group userData={{ name: 'Component_27_24' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh67.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh67' }}
                />
              </group>
              <group userData={{ name: 'Component_27_25' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh68.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh68' }}
                />
              </group>
              <group userData={{ name: 'Component_27_26' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh69.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh69' }}
                />
              </group>
              <group userData={{ name: 'Component_27_27' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh70.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh70' }}
                />
              </group>
              <group userData={{ name: 'Component_27_28' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh71.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh71' }}
                />
              </group>
              <group userData={{ name: 'Component_27_29' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh72.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh72' }}
                />
              </group>
              <group userData={{ name: 'Component_26_6' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh73.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh73' }}
                />
              </group>
              <group userData={{ name: 'Component_27_30' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh74.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh74' }}
                />
              </group>
              <group userData={{ name: 'Component_27_31' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh75.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh75' }}
                />
              </group>
              <group userData={{ name: 'Component_27_32' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh76.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh76' }}
                />
              </group>
            </group>
            <group userData={{ name: 'BBK_20X60X85' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh77.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh77' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_1_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh78.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh78' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh79.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh79' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_3' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh80.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh80' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_4' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh81.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh81' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh82.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh82' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_6' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh83.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh83' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_7' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh84.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh84' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_8' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh85.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh85' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_9' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh86.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh86' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_10' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh87.geometry}
                material={materials.Carrera_Marble}
                userData={{ name: 'Mesh87' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh88.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh88' }}
              />
            </group>
            <group userData={{ name: 'BBK_20X60X85_12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh89.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh89' }}
              />
            </group>
            <group visible={plint === 'CB1'} userData={{ name: 'CB1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh90.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh90' }}
              />
            </group>
            <group visible={plint === 'CB2'} userData={{ name: 'CB2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh91.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh91' }}
              />
            </group>
            <group
              visible={plint === 'Plint_CB8'}
              userData={{ name: 'Plint_CB8' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh92.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh92' }}
              />
            </group>
            <group visible={plint === 'CB4'} userData={{ name: 'CB4' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh93.geometry}
                material={materials._Color_M00_1}
                userData={{ name: 'Mesh93' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BBK 020X60X85.glb');
