/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\BBW 110X60X200.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  pintu: ['CR11', 'CR12', 'CR13'],
};
export const key = 'BBW_110X60X200'
export function Model({ pintu = '' }) {
  const { nodes, materials } = useGLTF('/BBW 110X60X200.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BBW_110X60X200_1' }}>
            <group userData={{ name: 'BBW_110X60X200' }}>
              <group userData={{ name: 'Group1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh1.geometry}
                  material={materials.White}
                  userData={{ name: 'Mesh1' }}
                />
              </group>
              <group userData={{ name: 'Group2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh2.geometry}
                  material={materials.White}
                  userData={{ name: 'Mesh2' }}
                />
              </group>
              <group userData={{ name: 'Mesh3' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.mesh_2.geometry}
                  material={materials.FrontColor}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.mesh_2_1.geometry}
                  material={materials.Color_008}
                />
              </group>
            </group>
            <group userData={{ name: 'BBW_110X60X200_1_2' }}>
              <group visible={pintu === 'CR13'} userData={{ name: 'CR13' }}>
                <group userData={{ name: 'Group3' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh4.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh4' }}
                  />
                </group>
                <group userData={{ name: 'Group4' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh5.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh5' }}
                  />
                </group>
              </group>
            </group>
            <group userData={{ name: 'BBW_110X60X200_2' }}>
              <group visible={pintu === 'CR12'} userData={{ name: 'CR12' }}>
                <group userData={{ name: 'Group5' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh6.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh6' }}
                  />
                </group>
                <group userData={{ name: 'Group6' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh7.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh7' }}
                  />
                </group>
              </group>
            </group>
            <group visible={pintu === 'CR11'} userData={{ name: 'CR11' }}>
              <group userData={{ name: 'BBW_110X60X200_3' }}>
                <group userData={{ name: 'Group7' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh8.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh8' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'BBW_110X60X200_4' }}>
                <group userData={{ name: 'Group8' }}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh9.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh9' }}
                  />
                </group>
              </group>
            </group>
            <group userData={{ name: 'BBW_110X60X200_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh10.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh10' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_6' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh11.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh11' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_7' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh12.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh12' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_8' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh13.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh13' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_9' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh14.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh14' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_10' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh15.geometry}
                material={materials._Color_M00_1}
                userData={{ name: 'Mesh15' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_11' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh16.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh16' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh17.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh17' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_13' }}>
              <group userData={{ name: 'Component_1236_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh18.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh18' }}
                />
              </group>
              <group userData={{ name: 'Component_1237_1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh19.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh19' }}
                />
              </group>
              <group userData={{ name: 'Component_1237_2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh20.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh20' }}
                />
              </group>
            </group>
            <group userData={{ name: 'BBW_110X60X200_14' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh21.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh21' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_15' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh22.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh22' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_16' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh23.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh23' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_17' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh24.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh24' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_18' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh25.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh25' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BBW 110X60X200.glb');
