/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\KCH.06.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/KCH.06.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'KCH_06' }}>
            <group userData={{ name: 'KCH_06_1' }}>
              <mesh castShadow receiveShadow geometry={nodes.Mesh1.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh1' }} />
            </group>
            <group userData={{ name: 'Component_322_1' }}>
              <group userData={{ name: 'KCH_06_2' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh2.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh2' }} />
              </group>
              <group userData={{ name: 'KCH_06_3' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh3.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh3' }} />
              </group>
              <group userData={{ name: 'KCH_06_4' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh4.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh4' }} />
              </group>
              <group userData={{ name: 'KCH_06_5' }}>
                <group userData={{ name: 'Component_258_1' }}>
                  <mesh castShadow receiveShadow geometry={nodes.Mesh5.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh5' }} />
                </group>
              </group>
              <group userData={{ name: 'KCH_06_6' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh6.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh6' }} />
              </group>
              <group userData={{ name: 'KCH_06_7' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh7.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh7' }} />
              </group>
              <group userData={{ name: 'KCH_06_8' }}>
                <group userData={{ name: 'Component_421_1' }}>
                  <mesh castShadow receiveShadow geometry={nodes.Mesh8.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh8' }} />
                </group>
                <group userData={{ name: 'Component_433_1' }}>
                  <group userData={{ name: 'corbel_half_1_1' }}>
                    <group userData={{ name: 'Group1' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh9.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh9' }} />
                    </group>
                    <group userData={{ name: 'Group2' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh10.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh10' }} />
                    </group>
                    <group userData={{ name: 'Group3' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh11.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh11' }} />
                    </group>
                    <group userData={{ name: 'Group4' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh12.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh12' }} />
                    </group>
                    <group userData={{ name: 'Group5' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh13.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh13' }} />
                    </group>
                    <group userData={{ name: 'Group6' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh14.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh14' }} />
                    </group>
                    <group userData={{ name: 'Group7' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh15.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh15' }} />
                    </group>
                    <group userData={{ name: 'Group8' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh16.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh16' }} />
                    </group>
                  </group>
                  <group userData={{ name: 'corbel_half_1_2' }}>
                    <group userData={{ name: 'Group9' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh17.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh17' }} />
                    </group>
                    <group userData={{ name: 'Group10' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh18.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh18' }} />
                    </group>
                    <group userData={{ name: 'Group11' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh19.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh19' }} />
                    </group>
                    <group userData={{ name: 'Group12' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh20.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh20' }} />
                    </group>
                    <group userData={{ name: 'Group13' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh21.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh21' }} />
                    </group>
                    <group userData={{ name: 'Group14' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh22.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh22' }} />
                    </group>
                    <group userData={{ name: 'Group15' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh23.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh23' }} />
                    </group>
                    <group userData={{ name: 'Group16' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh24.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh24' }} />
                    </group>
                  </group>
                </group>
              </group>
              <group userData={{ name: 'KCH_06_9' }}>
                <group userData={{ name: 'Component_421_2' }}>
                  <mesh castShadow receiveShadow geometry={nodes.Mesh25.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh25' }} />
                </group>
                <group userData={{ name: 'Component_433_2' }}>
                  <group userData={{ name: 'corbel_half_1_3' }}>
                    <group userData={{ name: 'Group17' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh26.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh26' }} />
                    </group>
                    <group userData={{ name: 'Group18' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh27.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh27' }} />
                    </group>
                    <group userData={{ name: 'Group19' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh28.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh28' }} />
                    </group>
                    <group userData={{ name: 'Group20' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh29.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh29' }} />
                    </group>
                    <group userData={{ name: 'Group21' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh30.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh30' }} />
                    </group>
                    <group userData={{ name: 'Group22' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh31.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh31' }} />
                    </group>
                    <group userData={{ name: 'Group23' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh32.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh32' }} />
                    </group>
                    <group userData={{ name: 'Group24' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh33.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh33' }} />
                    </group>
                  </group>
                  <group userData={{ name: 'corbel_half_1_4' }}>
                    <group userData={{ name: 'Group25' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh34.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh34' }} />
                    </group>
                    <group userData={{ name: 'Group26' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh35.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh35' }} />
                    </group>
                    <group userData={{ name: 'Group27' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh36.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh36' }} />
                    </group>
                    <group userData={{ name: 'Group28' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh37.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh37' }} />
                    </group>
                    <group userData={{ name: 'Group29' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh38.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh38' }} />
                    </group>
                    <group userData={{ name: 'Group30' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh39.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh39' }} />
                    </group>
                    <group userData={{ name: 'Group31' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh40.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh40' }} />
                    </group>
                    <group userData={{ name: 'Group32' }}>
                      <mesh castShadow receiveShadow geometry={nodes.Mesh41.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh41' }} />
                    </group>
                  </group>
                </group>
              </group>
              <group userData={{ name: 'KCH_06_10' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh42.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh42' }} />
              </group>
              <group userData={{ name: 'KCH_06_11' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh43.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh43' }} />
              </group>
              <group userData={{ name: 'KCH_06_12' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh44.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh44' }} />
              </group>
              <group userData={{ name: 'KCH_06_13' }}>
                <mesh castShadow receiveShadow geometry={nodes.Mesh45.geometry} material={materials._Color_M00_1} userData={{ name: 'Mesh45' }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/KCH.06.glb')
