/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\PAL 90x25.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {};

export function Model() {
  const { nodes, materials } = useGLTF('/PAL 90x25.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'PA_WADROBE_6X25CM1' }}>
            <group userData={{ name: 'PA_WADROBE_6X25CM' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group userData={{ name: 'PA_WADROBE_6X25CM12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group userData={{ name: 'PA_WADROBE_6X25CM2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh3' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/PAL 90x25.glb');
