/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\TPKRP 8x40.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {};

export function Model(props) {
  const { nodes, materials } = useGLTF('/TPKRP 8x40.glb');
  return (
    <group {...props} dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'PROFIL_ATAS_KIRI_8CM1' }}>
            <group userData={{ name: 'PROFIL_ATAS_KIRI_8CM' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group userData={{ name: 'PROFIL_ATAS_KIRI_8CM12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group userData={{ name: 'PROFIL_ATAS_KIRI_8CM2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh3' }}
              />
            </group>
          </group>
          <group
            userData={{ name: 'FILLER_KANAN_KITCHEN_ATAS_8x40CM_PROFIL_1_1' }}
          >
            <group
              userData={{ name: 'FILLER_KANAN_KITCHEN_ATAS_8x40CM_PROFIL' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh4.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh4' }}
              />
            </group>
            <group
              userData={{ name: 'FILLER_KANAN_KITCHEN_ATAS_8x40CM_PROFIL1' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh5.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh5' }}
              />
            </group>
            <group
              userData={{ name: 'FILLER_KANAN_KITCHEN_ATAS_8x40CM_PROFIL2' }}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh6.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh6' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/TPKRP 8x40.glb');
