/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\TPWLP 8x40.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {};

export function Model() {
  const { nodes, materials } = useGLTF('/TPWLP 8x40.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'FILLER_KANAN_WADROBE_8x40CM1' }}>
            <group userData={{ name: 'FILLER_KANAN_WADROBE_8x40CM' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group userData={{ name: 'FILLER_KANAN_WADROBE_8x40CM12' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group userData={{ name: 'FILLER_KANAN_WADROBE_8x40CM2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh3' }}
              />
            </group>
          </group>
          <group userData={{ name: 'PA_KANAN_WADROBE_8x25CM1' }}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh4.geometry}
              material={materials.Color_M00}
              userData={{ name: 'Mesh4' }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/TPWLP 8x40.glb');
