/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\TPWLP 8x212.glb -o .\src\components\output.jsx -m -K -s 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export const metadata = {
  kaki: ['CB_4', 'CB_1', 'CB_2', 'CB_8'],
};

export function Model({ kaki = '' }) {
  const { nodes, materials } = useGLTF('/TPWLP 8x212.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'FILLER_KIRI_WADROBE_8x212CM1' }}>
            <group userData={{ name: 'FILLER_KIRI_WADROBE_8x210CM' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group userData={{ name: 'FILLER_KIRI_WADROBE_8x210CM1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group visible={kaki === 'CB_4'} userData={{ name: 'CB_4' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh3' }}
              />
            </group>
            <group userData={{ name: 'FILLER_KIRI_WADROBE_8x210CM2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh4.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh4' }}
              />
            </group>
            <group visible={kaki === 'CB_1'} userData={{ name: 'CB_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh5.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh5' }}
              />
            </group>
            <group visible={kaki === 'CB_2'} userData={{ name: 'CB_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh6.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh6' }}
              />
            </group>
            <group visible={kaki === 'CB_8'} userData={{ name: 'CB_8' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh7.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh7' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/TPWLP 8x212.glb');
