/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/base6.glb -m -K 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model({ pintu = '', handle = '', isian = '', kaki = '' }) {
  const { nodes, materials } = useGLTF('/base6.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BBK_40X60X85__1_1' }}>
            <group visible={pintu === 'pintu3'} userData={{ name: 'pintu3' }}>
              <mesh
                geometry={nodes.Mesh1.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group visible={handle === 'Knob_1'} userData={{ name: 'Knob_1' }}>
              <mesh
                geometry={nodes.Mesh2.geometry}
                material={materials.MyFrontMaterial1}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group visible={pintu === 'pintu1'} userData={{ name: 'pintu1' }}>
              <mesh
                geometry={nodes.Mesh3.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh3' }}
              />
            </group>
            <group visible={pintu === 'pintu2'} userData={{ name: 'pintu2' }}>
              <mesh
                geometry={nodes.Mesh4.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh4' }}
              />
            </group>
            <group
              visible={handle === 'Handle_2_1'}
              userData={{ name: 'Handle_2_1' }}
            >
              <mesh
                geometry={nodes.Mesh18.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh18' }}
              />
            </group>
            <group
              visible={handle === 'Handle_4_1'}
              userData={{ name: 'Handle_4_1' }}
            >
              <group userData={{ name: 'Group1' }}>
                <mesh
                  geometry={nodes.Mesh19.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh19' }}
                />
              </group>
              <group userData={{ name: 'OuterShell' }}>
                <mesh
                  geometry={nodes.Mesh20.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh20' }}
                />
              </group>
              <mesh
                geometry={nodes.Mesh21.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh21' }}
              />
            </group>
            <group
              visible={handle === 'Handle_3_1'}
              userData={{ name: 'Handle_3_1' }}
            >
              <mesh
                geometry={nodes.Mesh22.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh22' }}
              />
            </group>
            <group
              visible={handle === 'Handle_5__knob_1'}
              userData={{ name: 'Handle_5__knob_1' }}
            >
              <mesh
                geometry={nodes.Mesh23.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh23' }}
              />
            </group>
            <group
              visible={isian === 'Appliances_2_1'}
              userData={{ name: 'Appliances_2_1' }}
            >
              <group userData={{ name: 'BBK_040X60X85__3__WASTE_BIN' }}>
                <mesh
                  geometry={nodes.Mesh24.geometry}
                  material={materials.M_0134_DimGray}
                  userData={{ name: 'Mesh24' }}
                />
              </group>
              <group userData={{ name: 'Drawer_Slide_Closed1' }}>
                <group userData={{ name: 'Group2' }}>
                  <group userData={{ name: 'Mesh25' }}>
                    <mesh
                      geometry={nodes.mesh_24.geometry}
                      material={materials.Metal_Aluminum_Anodized}
                    />
                    <mesh
                      geometry={nodes.mesh_24_1.geometry}
                      material={materials.Metal_Aluminum_Anodized1}
                    />
                    <mesh
                      geometry={nodes.mesh_24_2.geometry}
                      material={materials.Metal_Aluminum_Anodized2}
                    />
                    <mesh
                      geometry={nodes.mesh_24_3.geometry}
                      material={materials.Metal_Aluminum_Anodized3}
                    />
                    <mesh
                      geometry={nodes.mesh_24_4.geometry}
                      material={materials.Metal_Aluminum_Anodized4}
                    />
                    <mesh
                      geometry={nodes.mesh_24_5.geometry}
                      material={materials.Metal_Aluminum_Anodized5}
                    />
                    <mesh
                      geometry={nodes.mesh_24_6.geometry}
                      material={materials.Metal_Aluminum_Anodized6}
                    />
                    <mesh
                      geometry={nodes.mesh_24_7.geometry}
                      material={materials.Metal_Aluminum_Anodized7}
                    />
                    <mesh
                      geometry={nodes.mesh_24_8.geometry}
                      material={materials.Metal_Aluminum_Anodized8}
                    />
                    <mesh
                      geometry={nodes.mesh_24_9.geometry}
                      material={materials.Metal_Aluminum_Anodized9}
                    />
                    <mesh
                      geometry={nodes.mesh_24_10.geometry}
                      material={materials.Metal_Aluminum_Anodized10}
                    />
                    <mesh
                      geometry={nodes.mesh_24_11.geometry}
                      material={materials.Metal_Aluminum_Anodized11}
                    />
                    <mesh
                      geometry={nodes.mesh_24_12.geometry}
                      material={materials.Metal_Aluminum_Anodized12}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group3' }}>
                  <mesh
                    geometry={nodes.Mesh26.geometry}
                    material={materials.Metal_Aluminum_Anodized}
                    userData={{ name: 'Mesh26' }}
                  />
                </group>
                <group userData={{ name: 'Group4' }}>
                  <mesh
                    geometry={nodes.Mesh27.geometry}
                    material={materials.Color_006}
                    userData={{ name: 'Mesh27' }}
                  />
                </group>
                <group userData={{ name: 'Group5' }}>
                  <mesh
                    geometry={nodes.Mesh28.geometry}
                    material={materials.Metal_Aluminum_Anodized}
                    userData={{ name: 'Mesh28' }}
                  />
                </group>
                <group userData={{ name: 'Group6' }}>
                  <mesh
                    geometry={nodes.Mesh29.geometry}
                    material={materials.Color_006}
                    userData={{ name: 'Mesh29' }}
                  />
                </group>
                <group userData={{ name: 'Group7' }}>
                  <mesh
                    geometry={nodes.Mesh30.geometry}
                    material={materials.Color_006}
                    userData={{ name: 'Mesh30' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'BBK_040X60X85__3__WASTE_BIN1' }}>
                <group userData={{ name: 'Group1_1' }}>
                  <mesh
                    geometry={nodes.Mesh31.geometry}
                    material={materials.M_0134_DimGray}
                    userData={{ name: 'Mesh31' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Drawer_Slide_Closed2' }}>
                <group userData={{ name: 'Group8' }}>
                  <group userData={{ name: 'Mesh32' }}>
                    <mesh
                      geometry={nodes.mesh_31.geometry}
                      material={materials.Metal_Aluminum_Anodized}
                    />
                    <mesh
                      geometry={nodes.mesh_31_1.geometry}
                      material={materials.Metal_Aluminum_Anodized1}
                    />
                    <mesh
                      geometry={nodes.mesh_31_2.geometry}
                      material={materials.Metal_Aluminum_Anodized2}
                    />
                    <mesh
                      geometry={nodes.mesh_31_3.geometry}
                      material={materials.Metal_Aluminum_Anodized3}
                    />
                    <mesh
                      geometry={nodes.mesh_31_4.geometry}
                      material={materials.Metal_Aluminum_Anodized4}
                    />
                    <mesh
                      geometry={nodes.mesh_31_5.geometry}
                      material={materials.Metal_Aluminum_Anodized5}
                    />
                    <mesh
                      geometry={nodes.mesh_31_6.geometry}
                      material={materials.Metal_Aluminum_Anodized6}
                    />
                    <mesh
                      geometry={nodes.mesh_31_7.geometry}
                      material={materials.Metal_Aluminum_Anodized7}
                    />
                    <mesh
                      geometry={nodes.mesh_31_8.geometry}
                      material={materials.Metal_Aluminum_Anodized8}
                    />
                    <mesh
                      geometry={nodes.mesh_31_9.geometry}
                      material={materials.Metal_Aluminum_Anodized9}
                    />
                    <mesh
                      geometry={nodes.mesh_31_10.geometry}
                      material={materials.Metal_Aluminum_Anodized10}
                    />
                    <mesh
                      geometry={nodes.mesh_31_11.geometry}
                      material={materials.Metal_Aluminum_Anodized11}
                    />
                    <mesh
                      geometry={nodes.mesh_31_12.geometry}
                      material={materials.Metal_Aluminum_Anodized12}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group9' }}>
                  <mesh
                    geometry={nodes.Mesh33.geometry}
                    material={materials.Metal_Aluminum_Anodized}
                    userData={{ name: 'Mesh33' }}
                  />
                </group>
                <group userData={{ name: 'Group10' }}>
                  <mesh
                    geometry={nodes.Mesh34.geometry}
                    material={materials.Color_006}
                    userData={{ name: 'Mesh34' }}
                  />
                </group>
                <group userData={{ name: 'Group11' }}>
                  <mesh
                    geometry={nodes.Mesh35.geometry}
                    material={materials.Metal_Aluminum_Anodized}
                    userData={{ name: 'Mesh35' }}
                  />
                </group>
                <group userData={{ name: 'Group12' }}>
                  <mesh
                    geometry={nodes.Mesh36.geometry}
                    material={materials.Color_006}
                    userData={{ name: 'Mesh36' }}
                  />
                </group>
                <group userData={{ name: 'Group13' }}>
                  <mesh
                    geometry={nodes.Mesh37.geometry}
                    material={materials.Color_006}
                    userData={{ name: 'Mesh37' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'BBK_040X60X85__3__WASTE_BIN2' }}>
                <mesh
                  geometry={nodes.Mesh38.geometry}
                  material={materials.M_0134_DimGray}
                  userData={{ name: 'Mesh38' }}
                />
              </group>
            </group>
            <group
              visible={isian === 'Ambalan_1_1'}
              userData={{ name: 'Ambalan_1_1' }}
            >
              <mesh
                geometry={nodes.Mesh39.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh39' }}
              />
            </group>
            <group
              visible={isian === 'Ambalan_2_1'}
              userData={{ name: 'Ambalan_2_1' }}
            >
              <group userData={{ name: 'BBK_40X60X85__1_13' }}>
                <mesh
                  geometry={nodes.Mesh40.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh40' }}
                />
              </group>
              <group userData={{ name: 'BBK_40X60X85__1_14' }}>
                <mesh
                  geometry={nodes.Mesh41.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh41' }}
                />
              </group>
            </group>
            <group
              visible={isian === 'Appliances_1_1'}
              userData={{ name: 'Appliances_1_1' }}
            >
              <group userData={{ name: 'Group14' }}>
                <group userData={{ name: 'Group15' }}>
                  <group userData={{ name: 'Group16' }}>
                    <group userData={{ name: 'Group17' }}>
                      <mesh
                        geometry={nodes.Mesh42.geometry}
                        material={materials.FrontColor}
                        userData={{ name: 'Mesh42' }}
                      />
                    </group>
                    <group userData={{ name: 'Group18' }}>
                      <mesh
                        geometry={nodes.Mesh43.geometry}
                        material={materials.Color_000}
                        userData={{ name: 'Mesh43' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh44' }}>
                      <mesh
                        geometry={nodes.mesh_43.geometry}
                        material={materials.FrontColor}
                      />
                      <mesh
                        geometry={nodes.mesh_43_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group19' }}>
                    <group userData={{ name: 'Group20' }}>
                      <group userData={{ name: 'Untitled1' }}>
                        <mesh
                          geometry={nodes.Mesh45.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh45' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled2' }}>
                        <mesh
                          geometry={nodes.Mesh46.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh46' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Group21' }}>
                      <group userData={{ name: 'Untitled3' }}>
                        <mesh
                          geometry={nodes.Mesh47.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh47' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled4' }}>
                        <mesh
                          geometry={nodes.Mesh48.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh48' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Mesh49' }}>
                      <mesh
                        geometry={nodes.mesh_48.geometry}
                        material={materials.FrontColor}
                      />
                      <mesh
                        geometry={nodes.mesh_48_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group22' }}>
                    <group userData={{ name: 'Group23' }}>
                      <group userData={{ name: 'Group24' }}>
                        <mesh
                          geometry={nodes.Mesh50.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh50' }}
                        />
                      </group>
                      <mesh
                        geometry={nodes.Mesh51.geometry}
                        material={materials.FrontColor}
                        userData={{ name: 'Mesh51' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh52' }}>
                      <mesh
                        geometry={nodes.mesh_51.geometry}
                        material={materials.FrontColor}
                      />
                      <mesh
                        geometry={nodes.mesh_51_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                </group>
                <group userData={{ name: 'Group26' }}>
                  <group userData={{ name: 'Group27' }}>
                    <group userData={{ name: 'Group28' }}>
                      <mesh
                        geometry={nodes.Mesh53.geometry}
                        material={materials.FrontColor}
                        userData={{ name: 'Mesh53' }}
                      />
                    </group>
                    <group userData={{ name: 'Group29' }}>
                      <mesh
                        geometry={nodes.Mesh54.geometry}
                        material={materials.Color_000}
                        userData={{ name: 'Mesh54' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh55' }}>
                      <mesh
                        geometry={nodes.mesh_54.geometry}
                        material={materials.FrontColor}
                      />
                      <mesh
                        geometry={nodes.mesh_54_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group30' }}>
                    <group userData={{ name: 'Group31' }}>
                      <group userData={{ name: 'Untitled5' }}>
                        <mesh
                          geometry={nodes.Mesh56.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh56' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled6' }}>
                        <mesh
                          geometry={nodes.Mesh57.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh57' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Group32' }}>
                      <group userData={{ name: 'Untitled7' }}>
                        <mesh
                          geometry={nodes.Mesh58.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh58' }}
                        />
                      </group>
                      <group userData={{ name: 'Untitled8' }}>
                        <mesh
                          geometry={nodes.Mesh59.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh59' }}
                        />
                      </group>
                    </group>
                    <group userData={{ name: 'Mesh60' }}>
                      <mesh
                        geometry={nodes.mesh_59.geometry}
                        material={materials.FrontColor}
                      />
                      <mesh
                        geometry={nodes.mesh_59_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                  <group userData={{ name: 'Group33' }}>
                    <group userData={{ name: 'Group34' }}>
                      <group userData={{ name: 'Group35' }}>
                        <mesh
                          geometry={nodes.Mesh61.geometry}
                          material={materials.FrontColor}
                          userData={{ name: 'Mesh61' }}
                        />
                      </group>
                      <mesh
                        geometry={nodes.Mesh62.geometry}
                        material={materials.FrontColor}
                        userData={{ name: 'Mesh62' }}
                      />
                    </group>
                    <group userData={{ name: 'Mesh63' }}>
                      <mesh
                        geometry={nodes.mesh_62.geometry}
                        material={materials.FrontColor}
                      />
                      <mesh
                        geometry={nodes.mesh_62_1.geometry}
                        material={materials.Color_000}
                      />
                    </group>
                  </group>
                </group>
              </group>
              <group userData={{ name: 'Group37' }}>
                <mesh
                  geometry={nodes.Mesh64.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh64' }}
                />
              </group>
              <group userData={{ name: 'Group38' }}>
                <mesh
                  geometry={nodes.Mesh65.geometry}
                  material={materials.papi_}
                  userData={{ name: 'Mesh65' }}
                />
              </group>
              <group userData={{ name: 'Group39' }}>
                <group userData={{ name: 'Group40' }}>
                  <group userData={{ name: 'Mesh66' }}>
                    <mesh
                      geometry={nodes.mesh_65.geometry}
                      material={materials.bottle}
                    />
                    <mesh
                      geometry={nodes.mesh_65_1.geometry}
                      material={materials.FrontColor}
                    />
                  </group>
                </group>
                <mesh
                  geometry={nodes.Mesh67.geometry}
                  material={materials.bottle}
                  userData={{ name: 'Mesh67' }}
                />
              </group>
              <group userData={{ name: 'Group41' }}>
                <group userData={{ name: 'Group42' }}>
                  <group userData={{ name: 'Mesh68' }}>
                    <mesh
                      geometry={nodes.mesh_67.geometry}
                      material={materials.bottle}
                    />
                    <mesh
                      geometry={nodes.mesh_67_1.geometry}
                      material={materials.FrontColor}
                    />
                  </group>
                </group>
                <mesh
                  geometry={nodes.Mesh69.geometry}
                  material={materials.bottle}
                  userData={{ name: 'Mesh69' }}
                />
              </group>
              <group userData={{ name: 'Group43' }}>
                <group userData={{ name: 'Mesh70' }}>
                  <mesh
                    geometry={nodes.mesh_69.geometry}
                    material={materials.FrontColor}
                  />
                  <mesh
                    geometry={nodes.mesh_69_1.geometry}
                    material={materials.whiskey_bottle}
                  />
                </group>
              </group>
              <group userData={{ name: 'BBK_40X60X85__2_' }}>
                <group userData={{ name: 'Group44' }}>
                  <mesh
                    geometry={nodes.Mesh71.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh71' }}
                  />
                </group>
                <group userData={{ name: 'Group45' }}>
                  <mesh
                    geometry={nodes.Mesh72.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh72' }}
                  />
                </group>
                <group userData={{ name: 'Group46' }}>
                  <mesh
                    geometry={nodes.Mesh73.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh73' }}
                  />
                </group>
                <group userData={{ name: 'Group47' }}>
                  <mesh
                    geometry={nodes.Mesh74.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh74' }}
                  />
                </group>
                <group userData={{ name: 'Group48' }}>
                  <mesh
                    geometry={nodes.Mesh75.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh75' }}
                  />
                </group>
                <group userData={{ name: 'Group49' }}>
                  <mesh
                    geometry={nodes.Mesh76.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh76' }}
                  />
                </group>
                <group userData={{ name: 'Group50' }}>
                  <group userData={{ name: 'Group51' }}>
                    <mesh
                      geometry={nodes.Mesh77.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh77' }}
                    />
                  </group>
                  <group userData={{ name: 'Group52' }}>
                    <mesh
                      geometry={nodes.Mesh78.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh78' }}
                    />
                  </group>
                  <group userData={{ name: 'Group53' }}>
                    <mesh
                      geometry={nodes.Mesh79.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh79' }}
                    />
                  </group>
                  <group userData={{ name: 'Group54' }}>
                    <mesh
                      geometry={nodes.Mesh80.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh80' }}
                    />
                  </group>
                  <group userData={{ name: 'Group55' }}>
                    <mesh
                      geometry={nodes.Mesh81.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh81' }}
                    />
                  </group>
                  <group userData={{ name: 'Group56' }}>
                    <mesh
                      geometry={nodes.Mesh82.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh82' }}
                    />
                  </group>
                  <group userData={{ name: 'Group57' }}>
                    <mesh
                      geometry={nodes.Mesh83.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh83' }}
                    />
                  </group>
                  <group userData={{ name: 'Group58' }}>
                    <mesh
                      geometry={nodes.Mesh84.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh84' }}
                    />
                  </group>
                  <group userData={{ name: 'Group59' }}>
                    <mesh
                      geometry={nodes.Mesh85.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh85' }}
                    />
                  </group>
                  <group userData={{ name: 'Group60' }}>
                    <mesh
                      geometry={nodes.Mesh86.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh86' }}
                    />
                  </group>
                  <group userData={{ name: 'Group61' }}>
                    <mesh
                      geometry={nodes.Mesh87.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh87' }}
                    />
                  </group>
                  <group userData={{ name: 'Group62' }}>
                    <mesh
                      geometry={nodes.Mesh88.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh88' }}
                    />
                  </group>
                  <group userData={{ name: 'Group63' }}>
                    <mesh
                      geometry={nodes.Mesh89.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh89' }}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group64' }}>
                  <mesh
                    geometry={nodes.Mesh90.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh90' }}
                  />
                </group>
                <group userData={{ name: 'Group65' }}>
                  <mesh
                    geometry={nodes.Mesh91.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh91' }}
                  />
                </group>
                <group userData={{ name: 'Group66' }}>
                  <group userData={{ name: 'Group67' }}>
                    <group userData={{ name: 'Group68' }}>
                      <mesh
                        geometry={nodes.Mesh92.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh92' }}
                      />
                    </group>
                    <group userData={{ name: 'Group69' }}>
                      <mesh
                        geometry={nodes.Mesh93.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh93' }}
                      />
                    </group>
                    <group userData={{ name: 'Group70' }}>
                      <mesh
                        geometry={nodes.Mesh94.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh94' }}
                      />
                    </group>
                    <group userData={{ name: 'Group71' }}>
                      <mesh
                        geometry={nodes.Mesh95.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh95' }}
                      />
                    </group>
                    <group userData={{ name: 'Group72' }}>
                      <mesh
                        geometry={nodes.Mesh96.geometry}
                        material={materials.Color_M00}
                        userData={{ name: 'Mesh96' }}
                      />
                    </group>
                    <mesh
                      geometry={nodes.Mesh97.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh97' }}
                    />
                  </group>
                  <group userData={{ name: 'Group73' }}>
                    <mesh
                      geometry={nodes.Mesh98.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh98' }}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group74' }}>
                  <group userData={{ name: 'Group75' }}>
                    <mesh
                      geometry={nodes.Mesh99.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh99' }}
                    />
                  </group>
                  <group userData={{ name: 'Group76' }}>
                    <mesh
                      geometry={nodes.Mesh100.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh100' }}
                    />
                  </group>
                  <group userData={{ name: 'Group77' }}>
                    <mesh
                      geometry={nodes.Mesh101.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh101' }}
                    />
                  </group>
                  <group userData={{ name: 'Group78' }}>
                    <mesh
                      geometry={nodes.Mesh102.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh102' }}
                    />
                  </group>
                  <group userData={{ name: 'Group79' }}>
                    <mesh
                      geometry={nodes.Mesh103.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh103' }}
                    />
                  </group>
                  <group userData={{ name: 'Group80' }}>
                    <mesh
                      geometry={nodes.Mesh104.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh104' }}
                    />
                  </group>
                  <group userData={{ name: 'Group81' }}>
                    <mesh
                      geometry={nodes.Mesh105.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh105' }}
                    />
                  </group>
                  <group userData={{ name: 'Group82' }}>
                    <mesh
                      geometry={nodes.Mesh106.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh106' }}
                    />
                  </group>
                  <group userData={{ name: 'Group83' }}>
                    <mesh
                      geometry={nodes.Mesh107.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh107' }}
                    />
                  </group>
                  <group userData={{ name: 'Group84' }}>
                    <mesh
                      geometry={nodes.Mesh108.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh108' }}
                    />
                  </group>
                  <group userData={{ name: 'Group85' }}>
                    <mesh
                      geometry={nodes.Mesh109.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh109' }}
                    />
                  </group>
                  <group userData={{ name: 'Group86' }}>
                    <mesh
                      geometry={nodes.Mesh110.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh110' }}
                    />
                  </group>
                  <group userData={{ name: 'Group87' }}>
                    <mesh
                      geometry={nodes.Mesh111.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh111' }}
                    />
                  </group>
                  <group userData={{ name: 'Group88' }}>
                    <mesh
                      geometry={nodes.Mesh112.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh112' }}
                    />
                  </group>
                  <group userData={{ name: 'Group89' }}>
                    <mesh
                      geometry={nodes.Mesh113.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh113' }}
                    />
                  </group>
                  <group userData={{ name: 'Group90' }}>
                    <mesh
                      geometry={nodes.Mesh114.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh114' }}
                    />
                  </group>
                  <group userData={{ name: 'Group91' }}>
                    <mesh
                      geometry={nodes.Mesh115.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh115' }}
                    />
                  </group>
                  <group userData={{ name: 'Group92' }}>
                    <mesh
                      geometry={nodes.Mesh116.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh116' }}
                    />
                  </group>
                  <group userData={{ name: 'Group93' }}>
                    <mesh
                      geometry={nodes.Mesh117.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh117' }}
                    />
                  </group>
                  <group userData={{ name: 'Group94' }}>
                    <mesh
                      geometry={nodes.Mesh118.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh118' }}
                    />
                  </group>
                  <group userData={{ name: 'Group95' }}>
                    <mesh
                      geometry={nodes.Mesh119.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh119' }}
                    />
                  </group>
                  <group userData={{ name: 'Group96' }}>
                    <mesh
                      geometry={nodes.Mesh120.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh120' }}
                    />
                  </group>
                  <group userData={{ name: 'Group97' }}>
                    <mesh
                      geometry={nodes.Mesh121.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh121' }}
                    />
                  </group>
                  <group userData={{ name: 'Group98' }}>
                    <mesh
                      geometry={nodes.Mesh122.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh122' }}
                    />
                  </group>
                  <group userData={{ name: 'Group99' }}>
                    <mesh
                      geometry={nodes.Mesh123.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh123' }}
                    />
                  </group>
                  <group userData={{ name: 'Group100' }}>
                    <mesh
                      geometry={nodes.Mesh124.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh124' }}
                    />
                  </group>
                  <group userData={{ name: 'Group101' }}>
                    <mesh
                      geometry={nodes.Mesh125.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh125' }}
                    />
                  </group>
                  <group userData={{ name: 'Group102' }}>
                    <mesh
                      geometry={nodes.Mesh126.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh126' }}
                    />
                  </group>
                  <group userData={{ name: 'Group103' }}>
                    <mesh
                      geometry={nodes.Mesh127.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh127' }}
                    />
                  </group>
                  <group userData={{ name: 'Group104' }}>
                    <mesh
                      geometry={nodes.Mesh128.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh128' }}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group105' }}>
                  <mesh
                    geometry={nodes.Mesh129.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh129' }}
                  />
                </group>
                <group userData={{ name: 'Group106' }}>
                  <mesh
                    geometry={nodes.Mesh130.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh130' }}
                  />
                </group>
                <group userData={{ name: 'Group107' }}>
                  <group userData={{ name: 'Group108' }}>
                    <mesh
                      geometry={nodes.Mesh131.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh131' }}
                    />
                  </group>
                  <group userData={{ name: 'Group109' }}>
                    <mesh
                      geometry={nodes.Mesh132.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh132' }}
                    />
                  </group>
                  <group userData={{ name: 'Group110' }}>
                    <mesh
                      geometry={nodes.Mesh133.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh133' }}
                    />
                  </group>
                  <group userData={{ name: 'Group111' }}>
                    <mesh
                      geometry={nodes.Mesh134.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh134' }}
                    />
                  </group>
                  <group userData={{ name: 'Group112' }}>
                    <mesh
                      geometry={nodes.Mesh135.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh135' }}
                    />
                  </group>
                  <group userData={{ name: 'Group113' }}>
                    <mesh
                      geometry={nodes.Mesh136.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh136' }}
                    />
                  </group>
                  <group userData={{ name: 'Group114' }}>
                    <mesh
                      geometry={nodes.Mesh137.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh137' }}
                    />
                  </group>
                  <group userData={{ name: 'Group115' }}>
                    <mesh
                      geometry={nodes.Mesh138.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh138' }}
                    />
                  </group>
                  <group userData={{ name: 'Group116' }}>
                    <mesh
                      geometry={nodes.Mesh139.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh139' }}
                    />
                  </group>
                  <group userData={{ name: 'Group117' }}>
                    <mesh
                      geometry={nodes.Mesh140.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh140' }}
                    />
                  </group>
                  <group userData={{ name: 'Group118' }}>
                    <mesh
                      geometry={nodes.Mesh141.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh141' }}
                    />
                  </group>
                  <group userData={{ name: 'Group119' }}>
                    <mesh
                      geometry={nodes.Mesh142.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh142' }}
                    />
                  </group>
                  <group userData={{ name: 'Group120' }}>
                    <mesh
                      geometry={nodes.Mesh143.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh143' }}
                    />
                  </group>
                  <group userData={{ name: 'Group121' }}>
                    <mesh
                      geometry={nodes.Mesh144.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh144' }}
                    />
                  </group>
                  <group userData={{ name: 'Group122' }}>
                    <mesh
                      geometry={nodes.Mesh145.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh145' }}
                    />
                  </group>
                  <group userData={{ name: 'Group123' }}>
                    <mesh
                      geometry={nodes.Mesh146.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh146' }}
                    />
                  </group>
                  <group userData={{ name: 'Group124' }}>
                    <mesh
                      geometry={nodes.Mesh147.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh147' }}
                    />
                  </group>
                  <group userData={{ name: 'Group125' }}>
                    <mesh
                      geometry={nodes.Mesh148.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh148' }}
                    />
                  </group>
                  <group userData={{ name: 'Group126' }}>
                    <mesh
                      geometry={nodes.Mesh149.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh149' }}
                    />
                  </group>
                  <group userData={{ name: 'Group127' }}>
                    <mesh
                      geometry={nodes.Mesh150.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh150' }}
                    />
                  </group>
                  <group userData={{ name: 'Group128' }}>
                    <mesh
                      geometry={nodes.Mesh151.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh151' }}
                    />
                  </group>
                  <group userData={{ name: 'Group129' }}>
                    <mesh
                      geometry={nodes.Mesh152.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh152' }}
                    />
                  </group>
                  <group userData={{ name: 'Group130' }}>
                    <mesh
                      geometry={nodes.Mesh153.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh153' }}
                    />
                  </group>
                  <group userData={{ name: 'Group131' }}>
                    <mesh
                      geometry={nodes.Mesh154.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh154' }}
                    />
                  </group>
                  <group userData={{ name: 'Group132' }}>
                    <mesh
                      geometry={nodes.Mesh155.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh155' }}
                    />
                  </group>
                  <group userData={{ name: 'Group133' }}>
                    <mesh
                      geometry={nodes.Mesh156.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh156' }}
                    />
                  </group>
                  <group userData={{ name: 'Group134' }}>
                    <mesh
                      geometry={nodes.Mesh157.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh157' }}
                    />
                  </group>
                  <group userData={{ name: 'Group135' }}>
                    <mesh
                      geometry={nodes.Mesh158.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh158' }}
                    />
                  </group>
                  <group userData={{ name: 'Group136' }}>
                    <mesh
                      geometry={nodes.Mesh159.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh159' }}
                    />
                  </group>
                  <group userData={{ name: 'Group137' }}>
                    <mesh
                      geometry={nodes.Mesh160.geometry}
                      material={materials.Color_M00}
                      userData={{ name: 'Mesh160' }}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Group138' }}>
                  <mesh
                    geometry={nodes.Mesh161.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh161' }}
                  />
                </group>
                <group userData={{ name: 'Group139' }}>
                  <mesh
                    geometry={nodes.Mesh162.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh162' }}
                  />
                </group>
                <group userData={{ name: 'Group140' }}>
                  <mesh
                    geometry={nodes.Mesh163.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh163' }}
                  />
                </group>
                <group userData={{ name: 'Group141' }}>
                  <mesh
                    geometry={nodes.Mesh164.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh164' }}
                  />
                </group>
                <group userData={{ name: 'Group142' }}>
                  <mesh
                    geometry={nodes.Mesh165.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh165' }}
                  />
                </group>
                <group userData={{ name: 'Group143' }}>
                  <mesh
                    geometry={nodes.Mesh166.geometry}
                    material={materials.Color_M00}
                    userData={{ name: 'Mesh166' }}
                  />
                </group>
              </group>
            </group>
            <group visible={kaki === 'CB8_1'} userData={{ name: 'CB8_1' }}>
              <mesh
                geometry={nodes.Mesh168.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh168' }}
              />
            </group>
            <group visible={kaki === 'CB2_1'} userData={{ name: 'CB2_1' }}>
              <mesh
                geometry={nodes.Mesh169.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh169' }}
              />
            </group>
            <group visible={kaki === 'CB1_1'} userData={{ name: 'CB1_1' }}>
              <mesh
                geometry={nodes.Mesh170.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh170' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_' }}>
              <mesh
                geometry={nodes.Mesh5.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh5' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_12' }}>
              <mesh
                geometry={nodes.Mesh6.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh6' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_2' }}>
              <mesh
                geometry={nodes.Mesh7.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh7' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_3' }}>
              <mesh
                geometry={nodes.Mesh8.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh8' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_4' }}>
              <mesh
                geometry={nodes.Mesh9.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh9' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_5' }}>
              <mesh
                geometry={nodes.Mesh10.geometry}
                material={materials.Carrera_Marble}
                userData={{ name: 'Mesh10' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_6' }}>
              <mesh
                geometry={nodes.Mesh11.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh11' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_7' }}>
              <mesh
                geometry={nodes.Mesh12.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh12' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_8' }}>
              <mesh
                geometry={nodes.Mesh13.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh13' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_9' }}>
              <mesh
                geometry={nodes.Mesh14.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh14' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_10' }}>
              <mesh
                geometry={nodes.Mesh15.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh15' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_11' }}>
              <mesh
                geometry={nodes.Mesh16.geometry}
                material={materials.MDF}
                userData={{ name: 'Mesh16' }}
              />
            </group>
            <group userData={{ name: 'BBK_40X60X85__1_1213' }}>
              <mesh
                geometry={nodes.Mesh17.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh17' }}
              />
            </group>

            <group userData={{ name: 'BBK_40X60X85__1_15' }}>
              <mesh
                geometry={nodes.Mesh167.geometry}
                material={materials._Color_M00_1}
                userData={{ name: 'Mesh167' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/base6.glb');
