/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/BAW 110X60X40.glb -o BAW110X60X40.jsx -K -m 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
export const metadata = {
  pintu: ['pintu1', 'pintu2', 'pintu3'],
  handle: ['handle1', 'handle2', 'handle3', 'handle4', 'handle5'],
  isian: ['ambalan1'],
};

export function Model({ pintu = '', handle = '', isian = '' }) {
  const { nodes, materials } = useGLTF('/BAW 110X60X40.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BAW_110X60X40_1' }}>
            <group visible={pintu === 'pintu1'} userData={{ name: 'pintu1' }}>
              <group userData={{ name: 'BAW_110X60X40' }}>
                <mesh
                  geometry={nodes.Mesh1.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh1' }}
                />
              </group>
              <group userData={{ name: 'BAW_110X60X40_1_2' }}>
                <mesh
                  geometry={nodes.Mesh2.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh2' }}
                />
              </group>
            </group>
            <group visible={pintu === 'pintu2'} userData={{ name: 'pintu2' }}>
              <group userData={{ name: 'BAW_110X60X40_2' }}>
                <mesh
                  geometry={nodes.Mesh3.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh3' }}
                />
              </group>
              <group userData={{ name: 'BAW_110X60X40_3' }}>
                <mesh
                  geometry={nodes.Mesh4.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh4' }}
                />
              </group>
            </group>
            <group visible={pintu === 'pintu3'} userData={{ name: 'pintu3' }}>
              <group userData={{ name: 'BAW_110X60X40_4' }}>
                <mesh
                  geometry={nodes.Mesh5.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh5' }}
                />
              </group>
              <group userData={{ name: 'BAW_110X60X40_5' }}>
                <mesh
                  geometry={nodes.Mesh6.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh6' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle1'}
              userData={{ name: 'handle1' }}
            >
              <group userData={{ name: 'Knob_1' }}>
                <mesh
                  geometry={nodes.Mesh7.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh7' }}
                />
              </group>
              <group userData={{ name: 'Knob_1_1' }}>
                <mesh
                  geometry={nodes.Mesh8.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh8' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle2'}
              userData={{ name: 'handle2' }}
            >
              <group userData={{ name: 'Handle_2_1' }}>
                <mesh
                  geometry={nodes.Mesh9.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh9' }}
                />
              </group>
              <group userData={{ name: 'Handle_2_2' }}>
                <mesh
                  geometry={nodes.Mesh10.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh10' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle3'}
              userData={{ name: 'handle3' }}
            >
              <group userData={{ name: 'Handle_3_1' }}>
                <mesh
                  geometry={nodes.Mesh11.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh11' }}
                />
              </group>
              <group userData={{ name: 'Handle_3_2' }}>
                <mesh
                  geometry={nodes.Mesh12.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh12' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle4'}
              userData={{ name: 'handle4' }}
            >
              <group userData={{ name: 'Handle_4_1' }}>
                <group userData={{ name: 'Group1' }}>
                  <mesh
                    geometry={nodes.Mesh13.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh13' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell' }}>
                  <mesh
                    geometry={nodes.Mesh14.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh14' }}
                  />
                </group>
                <mesh
                  geometry={nodes.Mesh15.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh15' }}
                />
              </group>
              <group userData={{ name: 'Handle_4_2' }}>
                <group userData={{ name: 'Group2' }}>
                  <mesh
                    geometry={nodes.Mesh16.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh16' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell1' }}>
                  <mesh
                    geometry={nodes.Mesh17.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh17' }}
                  />
                </group>
                <mesh
                  geometry={nodes.Mesh18.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh18' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle5'}
              userData={{ name: 'handle5' }}
            >
              <group userData={{ name: 'Handle_5__knob_1' }}>
                <mesh
                  geometry={nodes.Mesh19.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh19' }}
                />
              </group>
              <group userData={{ name: 'Handle_5__knob_2' }}>
                <mesh
                  geometry={nodes.Mesh20.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh20' }}
                />
              </group>
            </group>
            <group userData={{ name: 'BAW_110X60X40_6' }}>
              <mesh
                geometry={nodes.Mesh21.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh21' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_7' }}>
              <mesh
                geometry={nodes.Mesh22.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh22' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_8' }}>
              <mesh
                geometry={nodes.Mesh23.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh23' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_9' }}>
              <mesh
                geometry={nodes.Mesh24.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh24' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_10' }}>
              <mesh
                geometry={nodes.Mesh25.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh25' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_11' }}>
              <mesh
                geometry={nodes.Mesh26.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh26' }}
              />
            </group>
            <group
              visible={isian === 'ambalan1'}
              userData={{ name: 'ambalan1_1' }}
            >
              <mesh
                geometry={nodes.Mesh27.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh27' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BAW 110X60X40.glb');
