/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/BBW 110X60X200.glb -o BBW110X60X200.jsx -K -m 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
export const BbwMetadata = {
  pintu: ['pintu1', 'pintu2', 'pintu3'],
  handle: ['handle1', 'handle2', 'handle3', 'handle4', 'handle5'],
  isian: ['isian1', 'isian2', 'isian3', 'isian4', 'isian5'],
  kaki: ['kaki1', 'kaki2', 'kaki3', 'kaki4'],
};
export function Bbw({ pintu = '', handle = '', isian = '', kaki = '' }) {
  const { nodes, materials } = useGLTF('/BBW 110X60X200.glb');
  return (
    <group dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BBW_110X60X200_1' }}>
            <group visible={pintu === 'pintu1'} userData={{ name: 'pintu1' }}>
              <group userData={{ name: 'Group1' }}>
                <mesh
                  geometry={nodes.Mesh1.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh1' }}
                />
              </group>
              <group userData={{ name: 'Group2' }}>
                <mesh
                  geometry={nodes.Mesh2.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh2' }}
                />
              </group>
            </group>
            <group visible={pintu === 'pintu2'} userData={{ name: 'pintu2' }}>
              <group userData={{ name: 'Group3' }}>
                <mesh
                  geometry={nodes.Mesh3.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh3' }}
                />
              </group>
              <group userData={{ name: 'Group4' }}>
                <mesh
                  geometry={nodes.Mesh4.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh4' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle1'}
              userData={{ name: 'handle1' }}
            >
              <group userData={{ name: 'Handle_5__knob_1' }}>
                <mesh
                  geometry={nodes.Mesh5.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh5' }}
                />
              </group>
              <group userData={{ name: 'Handle_5__knob_2' }}>
                <mesh
                  geometry={nodes.Mesh6.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh6' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle2'}
              userData={{ name: 'handle2' }}
            >
              <group userData={{ name: 'Handle_4_1' }}>
                <group userData={{ name: 'Group5' }}>
                  <mesh
                    geometry={nodes.Mesh7.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh7' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell' }}>
                  <mesh
                    geometry={nodes.Mesh8.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh8' }}
                  />
                </group>
                <mesh
                  geometry={nodes.Mesh9.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh9' }}
                />
              </group>
              <group userData={{ name: 'Handle_4_2' }}>
                <group userData={{ name: 'Group6' }}>
                  <mesh
                    geometry={nodes.Mesh10.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh10' }}
                  />
                </group>
                <group userData={{ name: 'OuterShell1' }}>
                  <mesh
                    geometry={nodes.Mesh11.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh11' }}
                  />
                </group>
                <mesh
                  geometry={nodes.Mesh12.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh12' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle3'}
              userData={{ name: 'handle3' }}
            >
              <group userData={{ name: 'Handle_3_1' }}>
                <mesh
                  geometry={nodes.Mesh13.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh13' }}
                />
              </group>
              <group userData={{ name: 'Handle_3_2' }}>
                <mesh
                  geometry={nodes.Mesh14.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh14' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle4'}
              userData={{ name: 'handle4' }}
            >
              <group userData={{ name: 'Handle_2_1' }}>
                <mesh
                  geometry={nodes.Mesh15.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh15' }}
                />
              </group>
              <group userData={{ name: 'Handle_2_2' }}>
                <mesh
                  geometry={nodes.Mesh16.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh16' }}
                />
              </group>
            </group>
            <group
              visible={handle === 'handle5'}
              userData={{ name: 'handle5' }}
            >
              <group userData={{ name: 'Knob_1' }}>
                <mesh
                  geometry={nodes.Mesh17.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh17' }}
                />
              </group>
              <group userData={{ name: 'Knob_1_1' }}>
                <mesh
                  geometry={nodes.Mesh18.geometry}
                  material={materials.MyFrontMaterial1}
                  userData={{ name: 'Mesh18' }}
                />
              </group>
            </group>
            <group visible={pintu === 'pintu3'} userData={{ name: 'pintu3' }}>
              <group userData={{ name: 'BBW_110X60X200' }}>
                <group userData={{ name: 'Group7' }}>
                  <mesh
                    geometry={nodes.Mesh19.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh19' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'BBW_110X60X200_1_2' }}>
                <group userData={{ name: 'Group8' }}>
                  <mesh
                    geometry={nodes.Mesh20.geometry}
                    material={materials.FrontColor}
                    userData={{ name: 'Mesh20' }}
                  />
                </group>
              </group>
            </group>
            <group userData={{ name: 'BBW_110X60X200_2' }}>
              <mesh
                geometry={nodes.Mesh21.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh21' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_3' }}>
              <mesh
                geometry={nodes.Mesh22.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh22' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_4' }}>
              <mesh
                geometry={nodes.Mesh23.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh23' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_5' }}>
              <mesh
                geometry={nodes.Mesh24.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh24' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_6' }}>
              <mesh
                geometry={nodes.Mesh25.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh25' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_7' }}>
              <mesh
                geometry={nodes.Mesh26.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh26' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_8' }}>
              <mesh
                geometry={nodes.Mesh27.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh27' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_9' }}>
              <mesh
                geometry={nodes.Mesh28.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh28' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_10' }}>
              <mesh
                geometry={nodes.Mesh29.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh29' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_11' }}>
              <mesh
                geometry={nodes.Mesh30.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh30' }}
              />
            </group>
            <group userData={{ name: 'BBW_110X60X200_12' }}>
              <mesh
                geometry={nodes.Mesh31.geometry}
                material={materials.MDF_COKLAT}
                userData={{ name: 'Mesh31' }}
              />
            </group>
            <group visible={isian === 'isian1'} userData={{ name: 'isian1' }}>
              <group userData={{ name: 'Left_Group' }}>
                <group userData={{ name: 'Side_Plate' }}>
                  <mesh
                    geometry={nodes.Mesh32.geometry}
                    material={materials.Color_M06}
                    userData={{ name: 'Mesh32' }}
                  />
                </group>
                <group userData={{ name: 'Vertical_Bar' }}>
                  <group userData={{ name: 'Corner_Connector' }}>
                    <group userData={{ name: 'Mesh33' }}>
                      <mesh
                        geometry={nodes.mesh_32.geometry}
                        material={materials.Color_M06}
                      />
                      <mesh
                        geometry={nodes.mesh_32_1.geometry}
                        material={materials.Metal_Silver}
                      />
                    </group>
                  </group>
                  <mesh
                    geometry={nodes.Mesh34.geometry}
                    material={materials.Metal_Silver}
                    userData={{ name: 'Mesh34' }}
                  />
                </group>
              </group>
              <group userData={{ name: 'Rod_Horizontal' }}>
                <mesh
                  geometry={nodes.Mesh35.geometry}
                  material={materials.Metal_Silver}
                  userData={{ name: 'Mesh35' }}
                />
              </group>
              <group userData={{ name: 'Rod_Vertical' }}>
                <group userData={{ name: 'Mesh36' }}>
                  <mesh
                    geometry={nodes.mesh_35.geometry}
                    material={materials.Metal_Silver}
                  />
                  <mesh
                    geometry={nodes.mesh_35_1.geometry}
                    material={materials.Color_M06}
                  />
                </group>
              </group>
              <group userData={{ name: 'Right_Group' }}>
                <group userData={{ name: 'Side_Plate1' }}>
                  <group userData={{ name: 'Mesh37' }}>
                    <mesh
                      geometry={nodes.mesh_36.geometry}
                      material={materials.Color_M06}
                    />
                    <mesh
                      geometry={nodes.mesh_36_1.geometry}
                      material={materials.FrontColor}
                    />
                  </group>
                </group>
                <group userData={{ name: 'Vertical_Bar1' }}>
                  <group userData={{ name: 'Corner_Connector1' }}>
                    <group userData={{ name: 'Mesh38' }}>
                      <mesh
                        geometry={nodes.mesh_37.geometry}
                        material={materials.Color_M06}
                      />
                      <mesh
                        geometry={nodes.mesh_37_1.geometry}
                        material={materials.Metal_Silver}
                      />
                    </group>
                  </group>
                  <mesh
                    geometry={nodes.Mesh39.geometry}
                    material={materials.Metal_Silver}
                    userData={{ name: 'Mesh39' }}
                  />
                </group>
              </group>
            </group>
            <group visible={kaki === 'kaki1'} userData={{ name: 'kaki1' }}>
              <mesh
                geometry={nodes.Mesh40.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh40' }}
              />
            </group>
            <group visible={kaki === 'kaki3'} userData={{ name: 'kaki3' }}>
              <mesh
                geometry={nodes.Mesh41.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh41' }}
              />
            </group>
            <group visible={kaki === 'kaki4'} userData={{ name: 'kaki4_1' }}>
              <mesh
                geometry={nodes.Mesh42.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh42' }}
              />
            </group>
            <group visible={kaki === 'kaki2'} userData={{ name: 'kaki2' }}>
              <mesh
                geometry={nodes.Mesh43.geometry}
                material={materials._Color_M00_1}
                userData={{ name: 'Mesh43' }}
              />
            </group>
            <group visible={isian === 'isian3'} userData={{ name: 'isian3' }}>
              <group userData={{ name: 'Component_1236_1' }}>
                <mesh
                  geometry={nodes.Mesh44.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh44' }}
                />
              </group>
              <group userData={{ name: 'Component_1237_1' }}>
                <mesh
                  geometry={nodes.Mesh45.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh45' }}
                />
              </group>
              <group userData={{ name: 'Component_1237_2' }}>
                <mesh
                  geometry={nodes.Mesh46.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh46' }}
                />
              </group>
            </group>
            <group visible={isian === 'isian5'} userData={{ name: 'isian5' }}>
              <group userData={{ name: 'Component_3_1' }}>
                <mesh
                  geometry={nodes.Mesh47.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh47' }}
                />
              </group>
              <group userData={{ name: 'Component_3_2' }}>
                <mesh
                  geometry={nodes.Mesh48.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh48' }}
                />
              </group>
            </group>
            <group visible={isian === 'isian4'} userData={{ name: 'isian4' }}>
              <group userData={{ name: 'Component_3_3' }}>
                <mesh
                  geometry={nodes.Mesh49.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh49' }}
                />
              </group>
              <group userData={{ name: 'Component_3_4' }}>
                <mesh
                  geometry={nodes.Mesh50.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh50' }}
                />
              </group>
              <group userData={{ name: 'Component_3_5' }}>
                <mesh
                  geometry={nodes.Mesh51.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh51' }}
                />
              </group>
              <group userData={{ name: 'Component_3_6' }}>
                <mesh
                  geometry={nodes.Mesh52.geometry}
                  material={materials.Color_M00}
                  userData={{ name: 'Mesh52' }}
                />
              </group>
            </group>
            <group visible={isian === 'isian2'} userData={{ name: 'isian2' }}>
              <group userData={{ name: 'Component_1237_3' }}>
                <mesh
                  geometry={nodes.Mesh53.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh53' }}
                />
              </group>
              <group userData={{ name: 'Component_1237_4' }}>
                <mesh
                  geometry={nodes.Mesh54.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh54' }}
                />
              </group>
              <group userData={{ name: 'Component_1236_2' }}>
                <mesh
                  geometry={nodes.Mesh55.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh55' }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/BBW 110X60X200.glb');
