/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/atas_0.glb -K -m -s 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useCustomization } from '@/contexts/Customization';
export function Model(props) {
  const { nodes, materials } = useGLTF('/atas_0.glb');
  const customization = useCustomization();
  return (
    <group {...props} dispose={null}>
      <group>
        <group userData={{ name: 'Model' }}>
          <group userData={{ name: 'BAW_110X60X40_1' }}>
            <group userData={{ name: 'handle_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh1.geometry}
                material={materials.MyFrontMaterial1}
                userData={{ name: 'Mesh1' }}
              />
            </group>
            <group userData={{ name: 'handle_1_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh2.geometry}
                material={materials.MyFrontMaterial1}
                userData={{ name: 'Mesh2' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh3.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh3' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_1_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh4.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh4' }}
              />
            </group>
            <group userData={{ name: 'pintu_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh5.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh5' }}
              />
            </group>
            <group userData={{ name: 'pintu_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh6.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh6' }}
              />
            </group>
            <group userData={{ name: 'pintu_3' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh7.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh7' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh8.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh8' }}
              />
            </group>
            <group userData={{ name: 'pintu_2_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh9.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh9' }}
              />
            </group>
            <group userData={{ name: 'pintu_3_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh10.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh10' }}
              />
            </group>
            <group userData={{ name: 'pintu_1_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh11.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh11' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_3' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh12.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh12' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_4' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh13.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh13' }}
              />
            </group>
            <group userData={{ name: 'BAW_110X60X40_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh14.geometry}
                material={materials.Color_M00}
                userData={{ name: 'Mesh14' }}
              />
            </group>
            <group userData={{ name: 'handle_2' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh15.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh15' }}
              />
            </group>
            <group userData={{ name: 'handle_3' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh16.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh16' }}
              />
            </group>
            <group userData={{ name: 'handle_5' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh17.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh17' }}
              />
            </group>
            <group userData={{ name: 'handle_4' }}>
              <group userData={{ name: 'Group1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh18.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh18' }}
                />
              </group>
              <group userData={{ name: 'OuterShell' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh19.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh19' }}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh20.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh20' }}
              />
            </group>
            <group userData={{ name: 'handle_4_1' }}>
              <group userData={{ name: 'Group2' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh21.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh21' }}
                />
              </group>
              <group userData={{ name: 'OuterShell1' }}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Mesh22.geometry}
                  material={materials.FrontColor}
                  userData={{ name: 'Mesh22' }}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh23.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh23' }}
              />
            </group>
            <group userData={{ name: 'handle_2_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh24.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh24' }}
              />
            </group>
            <group userData={{ name: 'handle_5_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh25.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh25' }}
              />
            </group>
            <group userData={{ name: 'handle_3_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh26.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh26' }}
              />
            </group>
            <group userData={{ name: 'ambalan_1_1' }}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh27.geometry}
                material={materials.FrontColor}
                userData={{ name: 'Mesh27' }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/atas_0.glb');
